# 6. 자유자재로 데이터 가공하기.

## 데이터 전처리 - 원하는 형태로 데이터 가공하기
- dplyr 패키지
    - pandas에서 쓰는것들이 있었다.

In [4]:
library(dplyr)

Warning message:
"package 'dplyr' was built under R version 3.6.2"
Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [2]:

exam <- read.csv('./data/csv_exam.csv')
exam

   id class math english science
1   1 1     50   98      50
2   2 1     60   97      60
3   3 1     45   86      78
4   4 1     30   98      58
5   5 2     25   80      65
6   6 2     50   89      98
7   7 2     80   90      45
8   8 2     90   78      25
9   9 3     20   98      15
10 10 3     50   98      45
11 11 3     65   65      65
12 12 3     45   85      32
13 13 4     46   98      65
14 14 4     48   87      12
15 15 4     75   56      78
16 16 4     58   98      65
17 17 5     65   68      98
18 18 5     80   78      90
19 19 5     89   68      87
20 20 5     78   83      58

In [11]:
str(exam)

'data.frame':	20 obs. of  5 variables:
 $ id     : int  1 2 3 4 5 6 7 8 9 10 ...
 $ class  : int  1 1 1 1 2 2 2 2 3 3 ...
 $ math   : int  50 60 45 30 25 50 80 90 20 50 ...
 $ english: int  98 97 86 98 80 89 90 78 98 98 ...
 $ science: int  50 60 78 58 65 98 45 25 15 45 ...

In [12]:
summary(exam)

       id            class        math          english        science
 Min.   : 1.00   Min.   :1   Min.   :20.00   Min.   :56.0   Min.   :12.00
 1st Qu.: 5.75   1st Qu.:2   1st Qu.:45.75   1st Qu.:78.0   1st Qu.:45.00
 Median :10.50   Median :3   Median :54.00   Median :86.5   Median :62.50
 Mean   :10.50   Mean   :3   Mean   :57.45   Mean   :84.9   Mean   :59.45
 3rd Qu.:15.25   3rd Qu.:4   3rd Qu.:75.75   3rd Qu.:98.0   3rd Qu.:78.00
 Max.   :20.00   Max.   :5   Max.   :90.00   Max.   :98.0   Max.   :98.00

## 조건문  %>%  filter

In [5]:
# exam에서 class가 1 인 경우 추출 출력.
exam %>% filter(class == 1) # exam이란 애를 filter에 넣겠다.

  id class math english science
1 1  1     50   98      50
2 2  1     60   97      60
3 3  1     45   86      78
4 4  1     30   98      58

In [7]:
exam %>% filter(class == 2)

  id class math english science
1 5  2     25   80      65
2 6  2     50   89      98
3 7  2     80   90      45
4 8  2     90   78      25

In [6]:
exam %>% filter(class != 1)

   id class math english science
1   5 2     25   80      65
2   6 2     50   89      98
3   7 2     80   90      45
4   8 2     90   78      25
5   9 3     20   98      15
6  10 3     50   98      45
7  11 3     65   65      65
8  12 3     45   85      32
9  13 4     46   98      65
10 14 4     48   87      12
11 15 4     75   56      78
12 16 4     58   98      65
13 17 5     65   68      98
14 18 5     80   78      90
15 19 5     89   68      87
16 20 5     78   83      58

In [ ]:
# 비교되는 양이 적거나, 
# 나중에는 조건 튜닝, 하나라도 비교연산이 덜 들수 있는 구조로 바꾸는것.
## 가독성에 맞춰주는게 좋지만,

In [8]:
exam %>% filter(math < 50)

  id class math english science
1  3 1     45   86      78
2  4 1     30   98      58
3  5 2     25   80      65
4  9 3     20   98      15
5 12 3     45   85      32
6 13 4     46   98      65
7 14 4     48   87      12

## 다수 조건문, &

In [9]:
# 1반 이면서 수학 점수가 50점 이상인 경우
exam %>% filter(class == 1 & math >= 50)

  id class math english science
1 1  1     50   98      50
2 2  1     60   97      60

In [13]:
# 2반 이면서 영어점수가 80점 이상인 경우
exam %>% filter(class == 2 & english >= 80)

  id class math english science
1 5  2     25   80      65
2 6  2     50   89      98
3 7  2     80   90      45

In [14]:
# 수학 점수가 90점 이상이거나 영어점수가 90점 이상인 경우
exam %>% filter(math >= 90 | english >= 90)

  id class math english science
1  1 1     50   98      50
2  2 1     60   97      60
3  4 1     30   98      58
4  7 2     80   90      45
5  8 2     90   78      25
6  9 3     20   98      15
7 10 3     50   98      45
8 13 4     46   98      65
9 16 4     58   98      65

In [ ]:
# 영어점수가 90점 미만이거나 과학점수가 50점 미만인 경우
exam %>% filter(english < 90 | science < 50)

In [15]:
# 영어점수가 90점 미만이거나 과학점수가 50점 미만인 경우
exam %>% filter(class == 1 | class == 3 | class == 5 )

   id class math english science
1   1 1     50   98      50
2   2 1     60   97      60
3   3 1     45   86      78
4   4 1     30   98      58
5   9 3     20   98      15
6  10 3     50   98      45
7  11 3     65   65      65
8  12 3     45   85      32
9  17 5     65   68      98
10 18 5     80   78      90
11 19 5     89   68      87
12 20 5     78   83      58

### %IN%을 이용한 다중 or연산

In [16]:
# 위와 같지만, in연산쓴것.
exam %>% filter(class %in% c(1,3,5))

   id class math english science
1   1 1     50   98      50
2   2 1     60   97      60
3   3 1     45   86      78
4   4 1     30   98      58
5   9 3     20   98      15
6  10 3     50   98      45
7  11 3     65   65      65
8  12 3     45   85      32
9  17 5     65   68      98
10 18 5     80   78      90
11 19 5     89   68      87
12 20 5     78   83      58

### 추출한 데이터 행단위로 사용하기.

In [17]:
class1 <- exam %>% filter(class == 1)
class2 <- exam %>% filter(class == 2)

In [20]:
mean(class1$math); mean(class2$math)

[1] 46.25

[1] 61.25

^,** : 제곱
%/% : 나눗셈의 몫
%% : 나눗셈의 나머지

In [23]:
mpg <- as.data.frame(ggplot2::mpg)
mpg

    manufacturer model              displ year cyl trans      drv cty hwy fl
1   audi         a4                 1.8   1999 4   auto(l5)   f   18  29  p
2   audi         a4                 1.8   1999 4   manual(m5) f   21  29  p
3   audi         a4                 2.0   2008 4   manual(m6) f   20  31  p
4   audi         a4                 2.0   2008 4   auto(av)   f   21  30  p
5   audi         a4                 2.8   1999 6   auto(l5)   f   16  26  p
6   audi         a4                 2.8   1999 6   manual(m5) f   18  26  p
7   audi         a4                 3.1   2008 6   auto(av)   f   18  27  p
8   audi         a4 quattro         1.8   1999 4   manual(m5) 4   18  26  p
9   audi         a4 quattro         1.8   1999 4   auto(l5)   4   16  25  p
10  audi         a4 quattro         2.0   2008 4   manual(m6) 4   20  28  p
11  audi         a4 quattro         2.0   2008 4   auto(s6)   4   19  27  p
12  audi         a4 quattro         2.8   1999 6   auto(l5)   4   15  25  p
13  audi         a4 quattro         2.8   1999 6   manual(m5) 4   17  25  p
14  audi         a4 quattro         3.1   2008 6   auto(s6)   4   17  25  p
15  audi         a4 quattro         3.1   2008 6   manual(m6) 4   15  25  p
16  audi         a6 quattro         2.8   1999 6   auto(l5)   4   15  24  p
17  audi         a6 quattro         3.1   2008 6   auto(s6)   4   17  25  p
18  audi         a6 quattro         4.2   2008 8   auto(s6)   4   16  23  p
19  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   14  20  r
20  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   11  15  e
21  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   14  20  r
22  chevrolet    c1500 suburban 2wd 5.7   1999 8   auto(l4)   r   13  17  r
23  chevrolet    c1500 suburban 2wd 6.0   2008 8   auto(l4)   r   12  17  r
24  chevrolet    corvette           5.7   1999 8   manual(m6) r   16  26  p
25  chevrolet    corvette           5.7   1999 8   auto(l4)   r   15  23  p
26  chevrolet    corvette           6.2   2008 8   manual(m6) r   16  26  p
27  chevrolet    corvette           6.2   2008 8   auto(s6)   r   15  25  p
28  chevrolet    corvette           7.0   2008 8   manual(m6) r   15  24  p
29  chevrolet    k1500 tahoe 4wd    5.3   2008 8   auto(l4)   4   14  19  r
30  chevrolet    k1500 tahoe 4wd    5.3   2008 8   auto(l4)   4   11  14  e
... ...          ...                ...   ...  ... ...        ... ... ... ...
205 toyota       toyota tacoma 4wd  3.4   1999 6   auto(l4)   4   15  19  r
206 toyota       toyota tacoma 4wd  4.0   2008 6   manual(m6) 4   15  18  r
207 toyota       toyota tacoma 4wd  4.0   2008 6   auto(l5)   4   16  20  r
208 volkswagen   gti                2.0   1999 4   manual(m5) f   21  29  r
209 volkswagen   gti                2.0   1999 4   auto(l4)   f   19  26  r
210 volkswagen   gti                2.0   2008 4   manual(m6) f   21  29  p
211 volkswagen   gti                2.0   2008 4   auto(s6)   f   22  29  p
212 volkswagen   gti                2.8   1999 6   manual(m5) f   17  24  r
213 volkswagen   jetta              1.9   1999 4   manual(m5) f   33  44  d
214 volkswagen   jetta              2.0   1999 4   manual(m5) f   21  29  r
215 volkswagen   jetta              2.0   1999 4   auto(l4)   f   19  26  r
216 volkswagen   jetta              2.0   2008 4   auto(s6)   f   22  29  p
217 volkswagen   jetta              2.0   2008 4   manual(m6) f   21  29  p
218 volkswagen   jetta              2.5   2008 5   auto(s6)   f   21  29  r
219 volkswagen   jetta              2.5   2008 5   manual(m5) f   21  29  r
220 volkswagen   jetta              2.8   1999 6   auto(l4)   f   16  23  r
221 volkswagen   jetta              2.8   1999 6   manual(m5) f   17  24  r
222 volkswagen   new beetle         1.9   1999 4   manual(m5) f   35  44  d
223 volkswagen   new beetle         1.9   1999 4   auto(l4)   f   29  41  d
224 volkswagen   new beetle         2.0   1999 4   manual(m5) f   21  29  r
225 volkswagen   new beetle         2.0   1999 4   auto(l4)   f   19  26  r
226 volkswagen   new beetle         2.5   2008 5   manual(m5) f   20  28  r
227 volkswagen   new beetle         2.5   2008 5   auto(s6)   f   20  29  r
228 volkswagen   passat             1.8   1999 4   manual(m5) f   21  29  p
229 volkswagen   passat             1.8   1999 4   auto(l5)   f   18  29  p
230 volkswagen   passat             2.0   2008 4   auto(s6)   f   19  28  p
231 volkswagen   passat             2.0   2008 4   manual(m6) f   21  29  p
232 volkswagen   passat             2.8   1999 6   auto(l5)   f   16  26  p
233 volkswagen   passat             2.8   1999 6   manual(m5) f   18  26  p
234 volkswagen   passat             3.6   2008 6   auto(s6)   f   17  26  p
    class
1   compact
2   compact
3   compact
4   compact
5   compact
6   compact
7   compact
8   compact
9   compact
10  compact
11  compact
12  compact
13  compact
14  compact
15  compact
16  midsize
17  midsize
18  midsize
19  suv
20  suv
21  suv
22  suv
23  suv
24  2seater
25  2seater
26  2seater
27  2seater
28  2seater
29  suv
30  suv
... ...
205 pickup
206 pickup
207 pickup
208 compact
209 compact
210 compact
211 compact
212 compact
213 compact
214 compact
215 compact
216 compact
217 compact
218 compact
219 compact
220 compact
221 compact
222 subcompact
223 subcompact
224 subcompact
225 subcompact
226 subcompact
227 subcompact
228 midsize
229 midsize
230 midsize
231 midsize
232 midsize
233 midsize
234 midsize

In [24]:
str(mpg)

'data.frame':	234 obs. of  11 variables:
 $ manufacturer: chr  "audi" "audi" "audi" "audi" ...
 $ model       : chr  "a4" "a4" "a4" "a4" ...
 $ displ       : num  1.8 1.8 2 2 2.8 2.8 3.1 1.8 1.8 2 ...
 $ year        : int  1999 1999 2008 2008 1999 1999 2008 1999 1999 2008 ...
 $ cyl         : int  4 4 4 4 6 6 6 4 4 4 ...
 $ trans       : chr  "auto(l5)" "manual(m5)" "manual(m6)" "auto(av)" ...
 $ drv         : chr  "f" "f" "f" "f" ...
 $ cty         : int  18 21 20 21 16 18 18 18 16 20 ...
 $ hwy         : int  29 29 31 30 26 26 27 26 25 28 ...
 $ fl          : chr  "p" "p" "p" "p" ...
 $ class       : chr  "compact" "compact" "compact" "compact" ...

In [25]:
summary(mpg)

 manufacturer          model               displ            year
 Length:234         Length:234         Min.   :1.600   Min.   :1999
 Class :character   Class :character   1st Qu.:2.400   1st Qu.:1999
 Mode  :character   Mode  :character   Median :3.300   Median :2004
                                       Mean   :3.472   Mean   :2004
                                       3rd Qu.:4.600   3rd Qu.:2008
                                       Max.   :7.000   Max.   :2008
      cyl           trans               drv                 cty
 Min.   :4.000   Length:234         Length:234         Min.   : 9.00
 1st Qu.:4.000   Class :character   Class :character   1st Qu.:14.00
 Median :6.000   Mode  :character   Mode  :character   Median :17.00
 Mean   :5.889                                         Mean   :16.86
 3rd Qu.:8.000                                         3rd Qu.:19.00
 Max.   :8.000                                         Max.   :35.00
      hwy             fl               class
 Min.   :12.00   Length:234         Length:234
 1st Qu.:18.00   Class :character   Class :character
 Median :24.00   Mode  :character   Mode  :character
 Mean   :23.44
 3rd Qu.:27.00
 Max.   :44.00

# 혼자해보기

## Q1 - 자동차 배기량에 따라 고속도로 연비가 다른지 알아보려고 합니다. `displ`(배기량)이 `4` 이하인 자동차와 `5` 이상인 자동차 중 어떤 자동차의 `hwy`(고속도로 연비)가 평균적으로 더 높은지 알아보세요.

In [26]:
displ4 <- mpg %>% filter(mpg$displ <= 4)
displ4

    manufacturer model             displ year cyl trans      drv cty hwy fl
1   audi         a4                1.8   1999 4   auto(l5)   f   18  29  p
2   audi         a4                1.8   1999 4   manual(m5) f   21  29  p
3   audi         a4                2.0   2008 4   manual(m6) f   20  31  p
4   audi         a4                2.0   2008 4   auto(av)   f   21  30  p
5   audi         a4                2.8   1999 6   auto(l5)   f   16  26  p
6   audi         a4                2.8   1999 6   manual(m5) f   18  26  p
7   audi         a4                3.1   2008 6   auto(av)   f   18  27  p
8   audi         a4 quattro        1.8   1999 4   manual(m5) 4   18  26  p
9   audi         a4 quattro        1.8   1999 4   auto(l5)   4   16  25  p
10  audi         a4 quattro        2.0   2008 4   manual(m6) 4   20  28  p
11  audi         a4 quattro        2.0   2008 4   auto(s6)   4   19  27  p
12  audi         a4 quattro        2.8   1999 6   auto(l5)   4   15  25  p
13  audi         a4 quattro        2.8   1999 6   manual(m5) 4   17  25  p
14  audi         a4 quattro        3.1   2008 6   auto(s6)   4   17  25  p
15  audi         a4 quattro        3.1   2008 6   manual(m6) 4   15  25  p
16  audi         a6 quattro        2.8   1999 6   auto(l5)   4   15  24  p
17  audi         a6 quattro        3.1   2008 6   auto(s6)   4   17  25  p
18  chevrolet    malibu            2.4   1999 4   auto(l4)   f   19  27  r
19  chevrolet    malibu            2.4   2008 4   auto(l4)   f   22  30  r
20  chevrolet    malibu            3.1   1999 6   auto(l4)   f   18  26  r
21  chevrolet    malibu            3.5   2008 6   auto(l4)   f   18  29  r
22  chevrolet    malibu            3.6   2008 6   auto(s6)   f   17  26  r
23  dodge        caravan 2wd       2.4   1999 4   auto(l3)   f   18  24  r
24  dodge        caravan 2wd       3.0   1999 6   auto(l4)   f   17  24  r
25  dodge        caravan 2wd       3.3   1999 6   auto(l4)   f   16  22  r
26  dodge        caravan 2wd       3.3   1999 6   auto(l4)   f   16  22  r
27  dodge        caravan 2wd       3.3   2008 6   auto(l4)   f   17  24  r
28  dodge        caravan 2wd       3.3   2008 6   auto(l4)   f   17  24  r
29  dodge        caravan 2wd       3.3   2008 6   auto(l4)   f   11  17  e
30  dodge        caravan 2wd       3.8   1999 6   auto(l4)   f   15  22  r
... ...          ...               ...   ...  ... ...        ... ... ... ...
134 toyota       toyota tacoma 4wd 3.4   1999 6   auto(l4)   4   15  19  r
135 toyota       toyota tacoma 4wd 4.0   2008 6   manual(m6) 4   15  18  r
136 toyota       toyota tacoma 4wd 4.0   2008 6   auto(l5)   4   16  20  r
137 volkswagen   gti               2.0   1999 4   manual(m5) f   21  29  r
138 volkswagen   gti               2.0   1999 4   auto(l4)   f   19  26  r
139 volkswagen   gti               2.0   2008 4   manual(m6) f   21  29  p
140 volkswagen   gti               2.0   2008 4   auto(s6)   f   22  29  p
141 volkswagen   gti               2.8   1999 6   manual(m5) f   17  24  r
142 volkswagen   jetta             1.9   1999 4   manual(m5) f   33  44  d
143 volkswagen   jetta             2.0   1999 4   manual(m5) f   21  29  r
144 volkswagen   jetta             2.0   1999 4   auto(l4)   f   19  26  r
145 volkswagen   jetta             2.0   2008 4   auto(s6)   f   22  29  p
146 volkswagen   jetta             2.0   2008 4   manual(m6) f   21  29  p
147 volkswagen   jetta             2.5   2008 5   auto(s6)   f   21  29  r
148 volkswagen   jetta             2.5   2008 5   manual(m5) f   21  29  r
149 volkswagen   jetta             2.8   1999 6   auto(l4)   f   16  23  r
150 volkswagen   jetta             2.8   1999 6   manual(m5) f   17  24  r
151 volkswagen   new beetle        1.9   1999 4   manual(m5) f   35  44  d
152 volkswagen   new beetle        1.9   1999 4   auto(l4)   f   29  41  d
153 volkswagen   new beetle        2.0   1999 4   manual(m5) f   21  29  r
154 volkswagen   new beetle        2.0   1999 4   auto(l4)   f   19  26  r
155 volkswagen   new beetle        2.5   2008 5   manual(m5) f   20  28  r
156 volkswagen   new beetle        2.5   2008 5   auto(s6)   f   20  29  r
157 volkswagen   passat            1.8   1999 4   manual(m5) f   21  29  p
158 volkswagen   passat            1.8   1999 4   auto(l5)   f   18  29  p
159 volkswagen   passat            2.0   2008 4   auto(s6)   f   19  28  p
160 volkswagen   passat            2.0   2008 4   manual(m6) f   21  29  p
161 volkswagen   passat            2.8   1999 6   auto(l5)   f   16  26  p
162 volkswagen   passat            2.8   1999 6   manual(m5) f   18  26  p
163 volkswagen   passat            3.6   2008 6   auto(s6)   f   17  26  p
    class
1   compact
2   compact
3   compact
4   compact
5   compact
6   compact
7   compact
8   compact
9   compact
10  compact
11  compact
12  compact
13  compact
14  compact
15  compact
16  midsize
17  midsize
18  midsize
19  midsize
20  midsize
21  midsize
22  midsize
23  minivan
24  minivan
25  minivan
26  minivan
27  minivan
28  minivan
29  minivan
30  minivan
... ...
134 pickup
135 pickup
136 pickup
137 compact
138 compact
139 compact
140 compact
141 compact
142 compact
143 compact
144 compact
145 compact
146 compact
147 compact
148 compact
149 compact
150 compact
151 subcompact
152 subcompact
153 subcompact
154 subcompact
155 subcompact
156 subcompact
157 midsize
158 midsize
159 midsize
160 midsize
161 midsize
162 midsize
163 midsize

In [27]:
displ5 <- mpg %>% filter(mpg$displ >= 5)
displ5

   manufacturer model                  displ year cyl trans      drv cty hwy fl
1  chevrolet    c1500 suburban 2wd     5.3   2008 8   auto(l4)   r   14  20  r
2  chevrolet    c1500 suburban 2wd     5.3   2008 8   auto(l4)   r   11  15  e
3  chevrolet    c1500 suburban 2wd     5.3   2008 8   auto(l4)   r   14  20  r
4  chevrolet    c1500 suburban 2wd     5.7   1999 8   auto(l4)   r   13  17  r
5  chevrolet    c1500 suburban 2wd     6.0   2008 8   auto(l4)   r   12  17  r
6  chevrolet    corvette               5.7   1999 8   manual(m6) r   16  26  p
7  chevrolet    corvette               5.7   1999 8   auto(l4)   r   15  23  p
8  chevrolet    corvette               6.2   2008 8   manual(m6) r   16  26  p
9  chevrolet    corvette               6.2   2008 8   auto(s6)   r   15  25  p
10 chevrolet    corvette               7.0   2008 8   manual(m6) r   15  24  p
11 chevrolet    k1500 tahoe 4wd        5.3   2008 8   auto(l4)   4   14  19  r
12 chevrolet    k1500 tahoe 4wd        5.3   2008 8   auto(l4)   4   11  14  e
13 chevrolet    k1500 tahoe 4wd        5.7   1999 8   auto(l4)   4   11  15  r
14 chevrolet    k1500 tahoe 4wd        6.5   1999 8   auto(l4)   4   14  17  d
15 dodge        dakota pickup 4wd      5.2   1999 8   manual(m5) 4   11  17  r
16 dodge        dakota pickup 4wd      5.2   1999 8   auto(l4)   4   11  15  r
17 dodge        durango 4wd            5.2   1999 8   auto(l4)   4   11  16  r
18 dodge        durango 4wd            5.7   2008 8   auto(l5)   4   13  18  r
19 dodge        durango 4wd            5.9   1999 8   auto(l4)   4   11  15  r
20 dodge        ram 1500 pickup 4wd    5.2   1999 8   auto(l4)   4   11  15  r
21 dodge        ram 1500 pickup 4wd    5.2   1999 8   manual(m5) 4   11  16  r
22 dodge        ram 1500 pickup 4wd    5.7   2008 8   auto(l5)   4   13  17  r
23 dodge        ram 1500 pickup 4wd    5.9   1999 8   auto(l4)   4   11  15  r
24 ford         expedition 2wd         5.4   1999 8   auto(l4)   r   11  17  r
25 ford         expedition 2wd         5.4   2008 8   auto(l6)   r   12  18  r
26 ford         explorer 4wd           5.0   1999 8   auto(l4)   4   13  17  r
27 ford         f150 pickup 4wd        5.4   1999 8   auto(l4)   4   11  15  r
28 ford         f150 pickup 4wd        5.4   2008 8   auto(l4)   4   13  17  r
29 ford         mustang                5.4   2008 8   manual(m6) r   14  20  p
30 jeep         grand cherokee 4wd     5.7   2008 8   auto(l5)   4   13  18  r
31 jeep         grand cherokee 4wd     6.1   2008 8   auto(l5)   4   11  14  p
32 lincoln      navigator 2wd          5.4   1999 8   auto(l4)   r   11  17  r
33 lincoln      navigator 2wd          5.4   1999 8   auto(l4)   r   11  16  p
34 lincoln      navigator 2wd          5.4   2008 8   auto(l6)   r   12  18  r
35 mercury      mountaineer 4wd        5.0   1999 8   auto(l4)   4   13  17  r
36 nissan       pathfinder 4wd         5.6   2008 8   auto(s5)   4   12  18  p
37 pontiac      grand prix             5.3   2008 8   auto(s4)   f   16  25  p
38 toyota       land cruiser wagon 4wd 5.7   2008 8   auto(s6)   4   13  18  r
   class
1  suv
2  suv
3  suv
4  suv
5  suv
6  2seater
7  2seater
8  2seater
9  2seater
10 2seater
11 suv
12 suv
13 suv
14 suv
15 pickup
16 pickup
17 suv
18 suv
19 suv
20 pickup
21 pickup
22 pickup
23 pickup
24 suv
25 suv
26 suv
27 pickup
28 pickup
29 subcompact
30 suv
31 suv
32 suv
33 suv
34 suv
35 suv
36 suv
37 midsize
38 suv

In [28]:
mean(displ4$hwy); mean(displ5$hwy)

[1] 25.96319

[1] 18.07895

- Q2. 자동차 제조 회사에 따라 도시 연비가 다른지 알아보려고 합니다. `"audi"`와 `"toyota"` 중 어느 `manufacturer`(자동차 제조 회사)의 `cty`(도시 연비)가 평균적으로 더 높은지 알아보세요.

In [29]:
audi <- mpg %>% filter(mpg$manufacturer == 'audi')
audi

   manufacturer model      displ year cyl trans      drv cty hwy fl class
1  audi         a4         1.8   1999 4   auto(l5)   f   18  29  p  compact
2  audi         a4         1.8   1999 4   manual(m5) f   21  29  p  compact
3  audi         a4         2.0   2008 4   manual(m6) f   20  31  p  compact
4  audi         a4         2.0   2008 4   auto(av)   f   21  30  p  compact
5  audi         a4         2.8   1999 6   auto(l5)   f   16  26  p  compact
6  audi         a4         2.8   1999 6   manual(m5) f   18  26  p  compact
7  audi         a4         3.1   2008 6   auto(av)   f   18  27  p  compact
8  audi         a4 quattro 1.8   1999 4   manual(m5) 4   18  26  p  compact
9  audi         a4 quattro 1.8   1999 4   auto(l5)   4   16  25  p  compact
10 audi         a4 quattro 2.0   2008 4   manual(m6) 4   20  28  p  compact
11 audi         a4 quattro 2.0   2008 4   auto(s6)   4   19  27  p  compact
12 audi         a4 quattro 2.8   1999 6   auto(l5)   4   15  25  p  compact
13 audi         a4 quattro 2.8   1999 6   manual(m5) 4   17  25  p  compact
14 audi         a4 quattro 3.1   2008 6   auto(s6)   4   17  25  p  compact
15 audi         a4 quattro 3.1   2008 6   manual(m6) 4   15  25  p  compact
16 audi         a6 quattro 2.8   1999 6   auto(l5)   4   15  24  p  midsize
17 audi         a6 quattro 3.1   2008 6   auto(s6)   4   17  25  p  midsize
18 audi         a6 quattro 4.2   2008 8   auto(s6)   4   16  23  p  midsize

In [30]:
toyota <- mpg %>% filter(mpg$manufacturer == 'toyota')
toyota

   manufacturer model                  displ year cyl trans      drv cty hwy fl
1  toyota       4runner 4wd            2.7   1999 4   manual(m5) 4   15  20  r
2  toyota       4runner 4wd            2.7   1999 4   auto(l4)   4   16  20  r
3  toyota       4runner 4wd            3.4   1999 6   auto(l4)   4   15  19  r
4  toyota       4runner 4wd            3.4   1999 6   manual(m5) 4   15  17  r
5  toyota       4runner 4wd            4.0   2008 6   auto(l5)   4   16  20  r
6  toyota       4runner 4wd            4.7   2008 8   auto(l5)   4   14  17  r
7  toyota       camry                  2.2   1999 4   manual(m5) f   21  29  r
8  toyota       camry                  2.2   1999 4   auto(l4)   f   21  27  r
9  toyota       camry                  2.4   2008 4   manual(m5) f   21  31  r
10 toyota       camry                  2.4   2008 4   auto(l5)   f   21  31  r
11 toyota       camry                  3.0   1999 6   auto(l4)   f   18  26  r
12 toyota       camry                  3.0   1999 6   manual(m5) f   18  26  r
13 toyota       camry                  3.5   2008 6   auto(s6)   f   19  28  r
14 toyota       camry solara           2.2   1999 4   auto(l4)   f   21  27  r
15 toyota       camry solara           2.2   1999 4   manual(m5) f   21  29  r
16 toyota       camry solara           2.4   2008 4   manual(m5) f   21  31  r
17 toyota       camry solara           2.4   2008 4   auto(s5)   f   22  31  r
18 toyota       camry solara           3.0   1999 6   auto(l4)   f   18  26  r
19 toyota       camry solara           3.0   1999 6   manual(m5) f   18  26  r
20 toyota       camry solara           3.3   2008 6   auto(s5)   f   18  27  r
21 toyota       corolla                1.8   1999 4   auto(l3)   f   24  30  r
22 toyota       corolla                1.8   1999 4   auto(l4)   f   24  33  r
23 toyota       corolla                1.8   1999 4   manual(m5) f   26  35  r
24 toyota       corolla                1.8   2008 4   manual(m5) f   28  37  r
25 toyota       corolla                1.8   2008 4   auto(l4)   f   26  35  r
26 toyota       land cruiser wagon 4wd 4.7   1999 8   auto(l4)   4   11  15  r
27 toyota       land cruiser wagon 4wd 5.7   2008 8   auto(s6)   4   13  18  r
28 toyota       toyota tacoma 4wd      2.7   1999 4   manual(m5) 4   15  20  r
29 toyota       toyota tacoma 4wd      2.7   1999 4   auto(l4)   4   16  20  r
30 toyota       toyota tacoma 4wd      2.7   2008 4   manual(m5) 4   17  22  r
31 toyota       toyota tacoma 4wd      3.4   1999 6   manual(m5) 4   15  17  r
32 toyota       toyota tacoma 4wd      3.4   1999 6   auto(l4)   4   15  19  r
33 toyota       toyota tacoma 4wd      4.0   2008 6   manual(m6) 4   15  18  r
34 toyota       toyota tacoma 4wd      4.0   2008 6   auto(l5)   4   16  20  r
   class
1  suv
2  suv
3  suv
4  suv
5  suv
6  suv
7  midsize
8  midsize
9  midsize
10 midsize
11 midsize
12 midsize
13 midsize
14 compact
15 compact
16 compact
17 compact
18 compact
19 compact
20 compact
21 compact
22 compact
23 compact
24 compact
25 compact
26 suv
27 suv
28 pickup
29 pickup
30 pickup
31 pickup
32 pickup
33 pickup
34 pickup

In [31]:
mean(audi$cty); mean(toyota$cty)

[1] 17.61111

[1] 18.52941

- Q3. `"chevrolet"`, `"ford"`, `"honda"` 자동차의 고속도로 연비 평균을 알아보려고 합니다. 이 회사들의 자동차를 추출한 뒤 `hwy` 전체 평균을 구해보세요.

In [32]:
chevrolet <- mpg %>% filter(mpg$manufacturer == 'chevrolet')
ford <- mpg %>% filter(mpg$manufacturer == 'ford')
honda <- mpg %>% filter(mpg$manufacturer == 'honda')

In [33]:
mean(chevrolet$hwy); mean(ford$hwy); mean(honda$hwy)

[1] 21.89474

[1] 19.36

[1] 32.55556

# 컬럼벼로 추출하기
- 10am

In [34]:
# 필요 컬럼에 대해 출력.
exam %>% select(math)

   math
1  50
2  60
3  45
4  30
5  25
6  50
7  80
8  90
9  20
10 50
11 65
12 45
13 46
14 48
15 75
16 58
17 65
18 80
19 89
20 78

In [35]:
exam %>% select(english)

   english
1  98
2  97
3  86
4  98
5  80
6  89
7  90
8  78
9  98
10 98
11 65
12 85
13 98
14 87
15 56
16 98
17 68
18 78
19 68
20 83

In [36]:
exam %>% select(class,math,english)

   class math english
1  1     50   98
2  1     60   97
3  1     45   86
4  1     30   98
5  2     25   80
6  2     50   89
7  2     80   90
8  2     90   78
9  3     20   98
10 3     50   98
11 3     65   65
12 3     45   85
13 4     46   98
14 4     48   87
15 4     75   56
16 4     58   98
17 5     65   68
18 5     80   78
19 5     89   68
20 5     78   83

- select에서 - 는 그 컬럼만 빠진 모든것.

- 외부 인터페이스 되는지

In [ ]:
exam %>% select(-math)

- **데이터가 많이 걸러지는 순으로 필터를 걸면 좋다**
- 컬럼이 많은경우 select로 필수 컬럼만을 추출후 걸러내는게 좋다.

In [38]:
exam %>% filter(class==1)  %>% select(english)

  english
1 98
2 97
3 86
4 98

- 커서라인을 내려서 받을 수도 있다.

In [37]:
exam %>%
 filter(class==1)  %>%
 select(english)

  english
1 98
2 97
3 86
4 98

In [39]:
exam %>%
 select(id,math)  %>%
 head

  id math
1 1  50
2 2  60
3 3  45
4 4  30
5 5  25
6 6  50

In [40]:
exam %>%
 select(id,math)  %>%
 head(10)

   id math
1   1 50
2   2 60
3   3 45
4   4 30
5   5 25
6   6 50
7   7 80
8   8 90
9   9 20
10 10 50

## 혼자해보기
- mpg 데이터

In [ ]:
mpg <- as.data.frame(ggplot2::mpg)

Q1. `mpg` 데이터는 11개 변수로 구성되어 있습니다. 이 중 일부만 추출해서 분석에 활용하려고 합니다. `mpg` 데이터에서 `class`(자동차 종류), `cty`(도시 연비) 변수를 추출해 새로운 데이터를 만드세요. 새로 만든 데이터의 일부를 출력해서 두 변수로만 구성되어 있는지 확인하세요.

In [41]:
mpg_class_cty <- mpg %>% select(class,cty)
mpg_class_cty

    class      cty
1   compact    18
2   compact    21
3   compact    20
4   compact    21
5   compact    16
6   compact    18
7   compact    18
8   compact    18
9   compact    16
10  compact    20
11  compact    19
12  compact    15
13  compact    17
14  compact    17
15  compact    15
16  midsize    15
17  midsize    17
18  midsize    16
19  suv        14
20  suv        11
21  suv        14
22  suv        13
23  suv        12
24  2seater    16
25  2seater    15
26  2seater    16
27  2seater    15
28  2seater    15
29  suv        14
30  suv        11
... ...        ...
205 pickup     15
206 pickup     15
207 pickup     16
208 compact    21
209 compact    19
210 compact    21
211 compact    22
212 compact    17
213 compact    33
214 compact    21
215 compact    19
216 compact    22
217 compact    21
218 compact    21
219 compact    21
220 compact    16
221 compact    17
222 subcompact 35
223 subcompact 29
224 subcompact 21
225 subcompact 19
226 subcompact 20
227 subcompact 20
228 midsize    21
229 midsize    18
230 midsize    19
231 midsize    21
232 midsize    16
233 midsize    18
234 midsize    17

In [42]:
str(mpg_class_cty)

'data.frame':	234 obs. of  2 variables:
 $ class: chr  "compact" "compact" "compact" "compact" ...
 $ cty  : int  18 21 20 21 16 18 18 18 16 20 ...

Q2. 자동차 종류에 따라 도시 연비가 다른지 알아보려고 합니다. 앞에서 추출한 데이터를 이용해서 `class`(자동차 종류)가 `"suv"`인 자동차와 `"compact"`인 자동차 중 어떤 자동차의 `cty`(도시 연비)가 더 높은지 알아보세요.

In [49]:
# mpg_class_cty %>% filter(mpg_class_cty$class == 'suv')
# mpg_class_cty %>% filter(mpg_class_cty$class == 'suv') %>% select(cty)
# class(mpg_class_cty %>% filter(mpg_class_cty$class == 'suv') %>% select(cty))
mean(mpg_class_cty %>% filter(mpg_class_cty$class == 'suv') %>% select(cty))

ERROR: Error in .$select(cty): 2를 필요로 하는 '$'에 인자 3가 전달되었습니다

In [ ]:
mpg_class_cty %>% filter(mpg_class_cty$class == 'suv')

# 순서대로 정렬하기.

In [ ]:
exam %>% arrange(math)

In [ ]:
exam %>% arrange(desc(math))

In [ ]:
exam %>% arrange(class, math) # class기준으로 먼저정렬 후 math도 포함.

## 혼자해보기

In [ ]:
audi <- mpg %>% filter(mpg$manufacturer == 'audi') # 내림차순, 오름차순이니 (낮은 탑 5위, 높은 탑 5위 인가. )

In [50]:
audi$class

 [1] "compact" "compact" "compact" "compact" "compact" "compact" "compact"
 [8] "compact" "compact" "compact" "compact" "compact" "compact" "compact"
[15] "compact" "midsize" "midsize" "midsize"

# 파생변수 추가하기

In [51]:
exam %>% 
 mutate(total = math + english + science) %>%
 head

  id class math english science total
1 1  1     50   98      50      198
2 2  1     60   97      60      217
3 3  1     45   86      78      209
4 4  1     30   98      58      186
5 5  2     25   80      65      170
6 6  2     50   89      98      237

In [ ]:
exam %>%  #test라는 변수를 만들겠다.
 mutate(test = ifelse(science >= 60, "pass", "fail")) %>% 
 head

In [ ]:
# R에서도 처리하고 정렬을 한번에 하는 로직이 ㅁ낳다.
# 리스트 내포문과 람다 같이쓰는것처럼

## 혼자해보기

In [52]:
mpg_new <- mpg

In [53]:
str(mpg_new)

'data.frame':	234 obs. of  11 variables:
 $ manufacturer: chr  "audi" "audi" "audi" "audi" ...
 $ model       : chr  "a4" "a4" "a4" "a4" ...
 $ displ       : num  1.8 1.8 2 2 2.8 2.8 3.1 1.8 1.8 2 ...
 $ year        : int  1999 1999 2008 2008 1999 1999 2008 1999 1999 2008 ...
 $ cyl         : int  4 4 4 4 6 6 6 4 4 4 ...
 $ trans       : chr  "auto(l5)" "manual(m5)" "manual(m6)" "auto(av)" ...
 $ drv         : chr  "f" "f" "f" "f" ...
 $ cty         : int  18 21 20 21 16 18 18 18 16 20 ...
 $ hwy         : int  29 29 31 30 26 26 27 26 25 28 ...
 $ fl          : chr  "p" "p" "p" "p" ...
 $ class       : chr  "compact" "compact" "compact" "compact" ...

In [56]:
mpg_new <- mpg_new %>% 
 mutate(sum_cty_hwy = (mpg_new$cty + mpg_new$hwy)) %>% 
 head

In [57]:
str(mpg_new)

'data.frame':	6 obs. of  12 variables:
 $ manufacturer: chr  "audi" "audi" "audi" "audi" ...
 $ model       : chr  "a4" "a4" "a4" "a4" ...
 $ displ       : num  1.8 1.8 2 2 2.8 2.8
 $ year        : int  1999 1999 2008 2008 1999 1999
 $ cyl         : int  4 4 4 4 6 6
 $ trans       : chr  "auto(l5)" "manual(m5)" "manual(m6)" "auto(av)" ...
 $ drv         : chr  "f" "f" "f" "f" ...
 $ cty         : int  18 21 20 21 16 18
 $ hwy         : int  29 29 31 30 26 26
 $ fl          : chr  "p" "p" "p" "p" ...
 $ class       : chr  "compact" "compact" "compact" "compact" ...
 $ sum_cty_hwy : int  47 50 51 51 42 44

In [59]:
mpg_new <- mpg_new %>% 
 mutate(mean_cty_hwy = mpg_new$sum_cty_hwy /2 ) %>% 
 head

In [60]:
mpg_new

  manufacturer model displ year cyl trans      drv cty hwy fl class
1 audi         a4    1.8   1999 4   auto(l5)   f   18  29  p  compact
2 audi         a4    1.8   1999 4   manual(m5) f   21  29  p  compact
3 audi         a4    2.0   2008 4   manual(m6) f   20  31  p  compact
4 audi         a4    2.0   2008 4   auto(av)   f   21  30  p  compact
5 audi         a4    2.8   1999 6   auto(l5)   f   16  26  p  compact
6 audi         a4    2.8   1999 6   manual(m5) f   18  26  p  compact
  sum_cty_hwy mean_cty_hwy
1 47          23.5
2 50          25.0
3 51          25.5
4 51          25.5
5 42          21.0
6 44          22.0

In [61]:
mpg_new %>% arrange(desc(mean_cty_hwy)) %>% head(3)

  manufacturer model displ year cyl trans      drv cty hwy fl class
1 audi         a4    2.0   2008 4   manual(m6) f   20  31  p  compact
2 audi         a4    2.0   2008 4   auto(av)   f   21  30  p  compact
3 audi         a4    1.8   1999 4   manual(m5) f   21  29  p  compact
  sum_cty_hwy mean_cty_hwy
1 51          25.5
2 51          25.5
3 50          25.0

In [62]:
# 한줄로 만들기
## 변수에 담지 않았으므로 생성하여 작동하고 제거됨.
mpg %>% 
 mutate(total = cty + hwy
        , mean = total/2) %>% 
 arrange(desc(mean)) %>% 
 head(3)

  manufacturer model      displ year cyl trans      drv cty hwy fl class
1 volkswagen   new beetle 1.9   1999 4   manual(m5) f   35  44  d  subcompact
2 volkswagen   jetta      1.9   1999 4   manual(m5) f   33  44  d  compact
3 volkswagen   new beetle 1.9   1999 4   auto(l4)   f   29  41  d  subcompact
  total mean
1 79    39.5
2 77    38.5
3 70    35.0

# 집단별 요약하기
- sql에성 where에 having..?

In [63]:
exam %>% 
 group_by(class) %>% 
 summarise( mean_math = mean(math) # math 평균
           , sum_math = sum(math) # math 합계
           , medium_math = median(math) # 중앙값
           , n = n() # count!, 학생수 
          )

  class mean_math sum_math medium_math n
1 1     46.25     185      47.5        4
2 2     61.25     245      65.0        4
3 3     45.00     180      47.5        4
4 4     56.75     227      53.0        4
5 5     78.00     312      79.0        4

## 자주 사용하는 요약통계량
- mean
- sd() : 표준편차
- n() : 빈도 
- median() : 중앙값.

## 각 집단별로 다시 집단 나우기.

In [64]:
mpg %>% 
 group_by(manufacturer, drv) %>% 
 summarise(mean_cty = mean(cty)) %>% 
 head(10)

   manufacturer drv mean_cty
1  audi         4   16.81818
2  audi         f   18.85714
3  chevrolet    4   12.50000
4  chevrolet    f   18.80000
5  chevrolet    r   14.10000
6  dodge        4   12.00000
7  dodge        f   15.81818
8  ford         4   13.30769
9  ford         r   14.75000
10 honda        f   24.44444

 문제) 회사별로 "suv" 자동차의 도시 및 고속도로 통합 연비 평균을 구해 내림차순으로 정렬하고, 1~5위까지 출력하기

In [72]:
mpg %>% 
 group_by(manufacturer) %>% 
 filter(class == 'suv') %>% 
 summarise(mean = sum(cty , hwy) / 2 ) %>% 
 arrange(desc(mean)) %>% 
 head(5)

  manufacturer mean
1 ford         138.0
2 chevrolet    134.0
3 subaru       131.5
4 toyota       130.5
5 jeep         124.5

Q1. `mpg` 데이터의 `class`는 `"suv"`, `"compact"` 등 자동차를 특징에 따라 일곱 종류로 분류한 변수입니다. 어떤 차종의 연비가 높은지 비교해보려고 합니다. `class`별 `cty` 평균을 구해보세요.

In [74]:
mpg %>% 
 group_by(class) %>% 
 summarise(class_mean = mean(cty))

  class      class_mean
1 2seater    15.40000
2 compact    20.12766
3 midsize    18.75610
4 minivan    15.81818
5 pickup     13.00000
6 subcompact 20.37143
7 suv        13.50000

Q2. 앞 문제의 출력 결과는 `class` 값 알파벳 순으로 정렬되어 있습니다. 어떤 차종의 도시 연비가 높은지 쉽게 알아볼 수 있도록 `cty` 평균이 높은 순으로 정렬해 출력하세요.

In [75]:
mpg %>% 
 group_by(class) %>% 
 summarise(class_mean = mean(cty)) %>% 
 arrange(desc(class_mean))

  class      class_mean
1 subcompact 20.37143
2 compact    20.12766
3 midsize    18.75610
4 minivan    15.81818
5 2seater    15.40000
6 suv        13.50000
7 pickup     13.00000

Q3. 어떤 회사 자동차의 `hwy`(고속도로 연비)가 가장 높은지 알아보려고 합니다. `hwy` 평균이 가장 높은 회사 세 곳을 출력하세요.

In [76]:
mpg %>% 
 group_by(manufacturer) %>% 
 summarise(manufacturer_mean = mean(hwy)) %>% 
 arrange(desc(manufacturer_mean)) %>% 
 head(3)

  manufacturer manufacturer_mean
1 honda        32.55556
2 volkswagen   29.22222
3 hyundai      26.85714

In [77]:
str(mpg)

'data.frame':	234 obs. of  11 variables:
 $ manufacturer: chr  "audi" "audi" "audi" "audi" ...
 $ model       : chr  "a4" "a4" "a4" "a4" ...
 $ displ       : num  1.8 1.8 2 2 2.8 2.8 3.1 1.8 1.8 2 ...
 $ year        : int  1999 1999 2008 2008 1999 1999 2008 1999 1999 2008 ...
 $ cyl         : int  4 4 4 4 6 6 6 4 4 4 ...
 $ trans       : chr  "auto(l5)" "manual(m5)" "manual(m6)" "auto(av)" ...
 $ drv         : chr  "f" "f" "f" "f" ...
 $ cty         : int  18 21 20 21 16 18 18 18 16 20 ...
 $ hwy         : int  29 29 31 30 26 26 27 26 25 28 ...
 $ fl          : chr  "p" "p" "p" "p" ...
 $ class       : chr  "compact" "compact" "compact" "compact" ...

Q4. 어떤 회사에서 `"compact"`(경차) 차종을 가장 많이 생산하는지 알아보려고 합니다. 각 회사별 `"compact"` 차종 수를 내림차순으로 정렬해 출력하세요.

In [90]:
# 내가한 것
mpg %>% 
 group_by(manufacturer) %>% 
 filter(class == 'compact') %>%  # 필터를 먼저 걸어주고 그룹바이로 해야한다.
 summarise(compact_count = n()) %>% 
 arrange(desc(compact_count)) %>% 
 head()

  manufacturer compact_count
1 audi         15
2 volkswagen   14
3 toyota       12
4 subaru        4
5 nissan        2

In [ ]:
# 모범답안
mpg %>% 
 filter(class == 'compact') %>% 
 group_by(manufacturer) %>% 
 summarise(compact_count = n()) %>% 
 arrange(desc(compact_count)) %>% 
 head()

데이터 합치기 ( concat, merge )

In [91]:
# 중간고사 데이터 생성
test1 <- data.frame(id = c(1, 2, 3, 4, 5),
                    midterm = c(60, 80, 70, 90, 85))
# 기말고사 데이터 생성
test2 <- data.frame(id = c(1, 2, 3, 4, 5),
                    final = c(70, 83, 65, 95, 80))

In [92]:
test1

  id midterm
1 1  60
2 2  80
3 3  70
4 4  90
5 5  85

In [93]:
test2

  id final
1 1  70
2 2  83
3 3  65
4 4  95
5 5  80

In [94]:
total <- left_join(test1, test2, by='id') # id 기준.
total

  id midterm final
1 1  60      70
2 2  80      83
3 3  70      65
4 4  90      95
5 5  85      80

In [ ]:
# R 세로는 bind_row

##  혼자해보기

In [95]:
fuel <- data.frame(fl = c("c", "d", "e", "p", "r"),
                   price_fl = c(2.35, 2.38, 2.11, 2.76, 2.22),
                   stringsAsFactors = F)
fuel  # 출력

  fl price_fl
1 c  2.35
2 d  2.38
3 e  2.11
4 p  2.76
5 r  2.22

In [96]:
str(mpg)

'data.frame':	234 obs. of  11 variables:
 $ manufacturer: chr  "audi" "audi" "audi" "audi" ...
 $ model       : chr  "a4" "a4" "a4" "a4" ...
 $ displ       : num  1.8 1.8 2 2 2.8 2.8 3.1 1.8 1.8 2 ...
 $ year        : int  1999 1999 2008 2008 1999 1999 2008 1999 1999 2008 ...
 $ cyl         : int  4 4 4 4 6 6 6 4 4 4 ...
 $ trans       : chr  "auto(l5)" "manual(m5)" "manual(m6)" "auto(av)" ...
 $ drv         : chr  "f" "f" "f" "f" ...
 $ cty         : int  18 21 20 21 16 18 18 18 16 20 ...
 $ hwy         : int  29 29 31 30 26 26 27 26 25 28 ...
 $ fl          : chr  "p" "p" "p" "p" ...
 $ class       : chr  "compact" "compact" "compact" "compact" ...

In [97]:
mpg <- left_join(mpg,fuel,by='fl')
mpg

    manufacturer model              displ year cyl trans      drv cty hwy fl
1   audi         a4                 1.8   1999 4   auto(l5)   f   18  29  p
2   audi         a4                 1.8   1999 4   manual(m5) f   21  29  p
3   audi         a4                 2.0   2008 4   manual(m6) f   20  31  p
4   audi         a4                 2.0   2008 4   auto(av)   f   21  30  p
5   audi         a4                 2.8   1999 6   auto(l5)   f   16  26  p
6   audi         a4                 2.8   1999 6   manual(m5) f   18  26  p
7   audi         a4                 3.1   2008 6   auto(av)   f   18  27  p
8   audi         a4 quattro         1.8   1999 4   manual(m5) 4   18  26  p
9   audi         a4 quattro         1.8   1999 4   auto(l5)   4   16  25  p
10  audi         a4 quattro         2.0   2008 4   manual(m6) 4   20  28  p
11  audi         a4 quattro         2.0   2008 4   auto(s6)   4   19  27  p
12  audi         a4 quattro         2.8   1999 6   auto(l5)   4   15  25  p
13  audi         a4 quattro         2.8   1999 6   manual(m5) 4   17  25  p
14  audi         a4 quattro         3.1   2008 6   auto(s6)   4   17  25  p
15  audi         a4 quattro         3.1   2008 6   manual(m6) 4   15  25  p
16  audi         a6 quattro         2.8   1999 6   auto(l5)   4   15  24  p
17  audi         a6 quattro         3.1   2008 6   auto(s6)   4   17  25  p
18  audi         a6 quattro         4.2   2008 8   auto(s6)   4   16  23  p
19  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   14  20  r
20  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   11  15  e
21  chevrolet    c1500 suburban 2wd 5.3   2008 8   auto(l4)   r   14  20  r
22  chevrolet    c1500 suburban 2wd 5.7   1999 8   auto(l4)   r   13  17  r
23  chevrolet    c1500 suburban 2wd 6.0   2008 8   auto(l4)   r   12  17  r
24  chevrolet    corvette           5.7   1999 8   manual(m6) r   16  26  p
25  chevrolet    corvette           5.7   1999 8   auto(l4)   r   15  23  p
26  chevrolet    corvette           6.2   2008 8   manual(m6) r   16  26  p
27  chevrolet    corvette           6.2   2008 8   auto(s6)   r   15  25  p
28  chevrolet    corvette           7.0   2008 8   manual(m6) r   15  24  p
29  chevrolet    k1500 tahoe 4wd    5.3   2008 8   auto(l4)   4   14  19  r
30  chevrolet    k1500 tahoe 4wd    5.3   2008 8   auto(l4)   4   11  14  e
... ...          ...                ...   ...  ... ...        ... ... ... ...
205 toyota       toyota tacoma 4wd  3.4   1999 6   auto(l4)   4   15  19  r
206 toyota       toyota tacoma 4wd  4.0   2008 6   manual(m6) 4   15  18  r
207 toyota       toyota tacoma 4wd  4.0   2008 6   auto(l5)   4   16  20  r
208 volkswagen   gti                2.0   1999 4   manual(m5) f   21  29  r
209 volkswagen   gti                2.0   1999 4   auto(l4)   f   19  26  r
210 volkswagen   gti                2.0   2008 4   manual(m6) f   21  29  p
211 volkswagen   gti                2.0   2008 4   auto(s6)   f   22  29  p
212 volkswagen   gti                2.8   1999 6   manual(m5) f   17  24  r
213 volkswagen   jetta              1.9   1999 4   manual(m5) f   33  44  d
214 volkswagen   jetta              2.0   1999 4   manual(m5) f   21  29  r
215 volkswagen   jetta              2.0   1999 4   auto(l4)   f   19  26  r
216 volkswagen   jetta              2.0   2008 4   auto(s6)   f   22  29  p
217 volkswagen   jetta              2.0   2008 4   manual(m6) f   21  29  p
218 volkswagen   jetta              2.5   2008 5   auto(s6)   f   21  29  r
219 volkswagen   jetta              2.5   2008 5   manual(m5) f   21  29  r
220 volkswagen   jetta              2.8   1999 6   auto(l4)   f   16  23  r
221 volkswagen   jetta              2.8   1999 6   manual(m5) f   17  24  r
222 volkswagen   new beetle         1.9   1999 4   manual(m5) f   35  44  d
223 volkswagen   new beetle         1.9   1999 4   auto(l4)   f   29  41  d
224 volkswagen   new beetle         2.0   1999 4   manual(m5) f   21  29  r
225 volkswagen   new beetle         2.0   1999 4   auto(l4)   f   19  26  r
226 volkswagen   new beetle         2.5   2008 5   manual(m5) f   20  28  r
227 volkswagen   new beetle         2.5   2008 5   auto(s6)   f   20  29  r
228 volkswagen   passat             1.8   1999 4   manual(m5) f   21  29  p
229 volkswagen   passat             1.8   1999 4   auto(l5)   f   18  29  p
230 volkswagen   passat             2.0   2008 4   auto(s6)   f   19  28  p
231 volkswagen   passat             2.0   2008 4   manual(m6) f   21  29  p
232 volkswagen   passat             2.8   1999 6   auto(l5)   f   16  26  p
233 volkswagen   passat             2.8   1999 6   manual(m5) f   18  26  p
234 volkswagen   passat             3.6   2008 6   auto(s6)   f   17  26  p
    class      price_fl
1   compact    2.76
2   compact    2.76
3   compact    2.76
4   compact    2.76
5   compact    2.76
6   compact    2.76
7   compact    2.76
8   compact    2.76
9   compact    2.76
10  compact    2.76
11  compact    2.76
12  compact    2.76
13  compact    2.76
14  compact    2.76
15  compact    2.76
16  midsize    2.76
17  midsize    2.76
18  midsize    2.76
19  suv        2.22
20  suv        2.11
21  suv        2.22
22  suv        2.22
23  suv        2.22
24  2seater    2.76
25  2seater    2.76
26  2seater    2.76
27  2seater    2.76
28  2seater    2.76
29  suv        2.22
30  suv        2.11
... ...        ...
205 pickup     2.22
206 pickup     2.22
207 pickup     2.22
208 compact    2.22
209 compact    2.22
210 compact    2.76
211 compact    2.76
212 compact    2.22
213 compact    2.38
214 compact    2.22
215 compact    2.22
216 compact    2.76
217 compact    2.76
218 compact    2.22
219 compact    2.22
220 compact    2.22
221 compact    2.22
222 subcompact 2.38
223 subcompact 2.38
224 subcompact 2.22
225 subcompact 2.22
226 subcompact 2.22
227 subcompact 2.22
228 midsize    2.76
229 midsize    2.76
230 midsize    2.76
231 midsize    2.76
232 midsize    2.76
233 midsize    2.76
234 midsize    2.76

In [ ]:
# 분석도전

In [122]:
midwest <- as.data.frame(ggplot2::midwest)
midwest

    PID  county      state area  poptotal popdensity popwhite popblack
1   561  ADAMS       IL    0.052   66090   1270.9615   63917     1702
2   562  ALEXANDER   IL    0.014   10626    759.0000    7054     3496
3   563  BOND        IL    0.022   14991    681.4091   14477      429
4   564  BOONE       IL    0.017   30806   1812.1176   29344      127
5   565  BROWN       IL    0.018    5836    324.2222    5264      547
6   566  BUREAU      IL    0.050   35688    713.7600   35157       50
7   567  CALHOUN     IL    0.017    5322    313.0588    5298        1
8   568  CARROLL     IL    0.027   16805    622.4074   16519      111
9   569  CASS        IL    0.024   13437    559.8750   13384       16
10  570  CHAMPAIGN   IL    0.058  173025   2983.1897  146506    16559
11  571  CHRISTIAN   IL    0.042   34418    819.4762   34176       82
12  572  CLARK       IL    0.030   15921    530.7000   15842       10
13  573  CLAY        IL    0.028   14460    516.4286   14403        4
14  574  CLINTON     IL    0.029   33944   1170.4828   32688     1021
15  575  COLES       IL    0.030   51644   1721.4667   50177      925
16  576  COOK        IL    0.058 5105067  88018.3966 3204947  1317147
17  577  CRAWFORD    IL    0.026   19464    748.6154   19300       63
18  578  CUMBERLAND  IL    0.020   10670    533.5000   10627        5
19  579  DE KALB     IL    0.038   77932   2050.8421   72968     2069
20  580  DE WITT     IL    0.023   16516    718.0870   16387       25
21  581  DOUGLAS     IL    0.025   19464    778.5600   19280       16
22  582  DU PAGE     IL    0.020  781666  39083.3000  714905    15462
23  583  EDGAR       IL    0.036   19595    544.3056   19469       68
24  584  EDWARDS     IL    0.014    7440    531.4286    7401        6
25  585  EFFINGHAM   IL    0.028   31704   1132.2857   31523       12
26  586  FAYETTE     IL    0.044   20893    474.8409   20148      599
27  587  FORD        IL    0.030   14275    475.8333   14157       43
28  588  FRANKLIN    IL    0.025   40319   1612.7600   40068       36
29  589  FULTON      IL    0.052   38080    732.3077   37117      668
30  590  GALLATIN    IL    0.019    6909    363.6316    6842       42
... ...  ...         ...   ...   ...      ...        ...      ...
408 3023 OCONTO      WI    0.060  30226    503.7667   29926      18
409 3024 ONEIDA      WI    0.071  31679    446.1831   31320      58
410 3025 OUTAGAMIE   WI    0.037 140510   3797.5676  136043     206
411 3026 OZAUKEE     WI    0.015  72831   4855.4000   71676     492
412 3027 PEPIN       WI    0.014   7107    507.6429    7070       2
413 3028 PIERCE      WI    0.034  32765    963.6765   32366      82
414 3029 POLK        WI    0.055  34773    632.2364   34348      23
415 3030 PORTAGE     WI    0.048  61405   1279.2708   59972     161
416 3031 PRICE       WI    0.075  15600    208.0000   15479       7
417 3032 RACINE      WI    0.020 175034   8751.7000  152098   16999
418 3033 RICHLAND    WI    0.034  17521    515.3235   17411      12
419 3034 ROCK        WI    0.042 139510   3321.6667  130803    6638
420 3035 RUSK        WI    0.055  15079    274.1636   14821      31
421 3036 ST CROIX    WI    0.044  50251   1142.0682   49895      44
422 3037 SAUK        WI    0.050  46975    939.5000   46459      54
423 3038 SAWYER      WI    0.079  14181    179.5063   11962      18
424 3039 SHAWANO     WI    0.054  37157    688.0926   35251      42
425 3040 SHEBOYGAN   WI    0.032 103877   3246.1562  100389     430
426 3041 TAYLOR      WI    0.057  18901    331.5965   18807       2
427 3042 TREMPEALEAU WI    0.043  25263    587.5116   25160      12
428 3043 VERNON      WI    0.048  25617    533.6875   25509      12
429 3044 VILAS       WI    0.060  17707    295.1167   16116       9
430 3045 WALWORTH    WI    0.032  75000   2343.7500   72747     454
431 3046 WASHBURN    WI    0.050  13772    275.4400   13585      25
432 3047 WASHINGTON  WI    0.025  95328   3813.1200   94465     125
433 3048 WAUKESHA    WI    0.034 304715   8962.2059  298313    1096
434 3049 WAUPACA     WI    0.045  46104   1024.5333   45695      22
435 3050 WAUSHARA    WI    0.037  19385    523.9189   19094      29
436 3051 WINNEBAGO   WI    0.035 140320   4009.1429  136822     697
437 3052 WOOD        WI    0.048  73605   1533.4375   72157      90
    popamerindian popasian ... percollege percprof  poppovertyknown
1      98            249   ... 19.63139    4.355859   63628
2      19             48   ... 11.24331    2.870315   10529
3      35             16   ... 17.03382    4.488572   14235
4      46            150   ... 17.27895    4.197800   30337
5      14              5   ... 14.47600    3.367680    4815
6      65            195   ... 18.90462    3.275891   35107
7       8             15   ... 11.91739    3.209601    5241
8      30             61   ... 16.19712    3.055727   16455
9       8             23   ... 14.10765    3.206799   13081
10    331           8033   ... 41.29581   17.757448  154934
11     51             89   ... 13.56723    3.089998   33788
12     26             36   ... 15.11086    2.776225   15615
13     17             29   ... 13.68301    2.788432   14248
14     48            104   ... 15.38747    2.875296   32190
15     92            341   ... 25.17504    8.144563   45693
16  10289         188565   ... 28.01812    8.329964 5023523
17     34             48   ... 16.98581    3.334084   19123
18      6             26   ... 14.59789    2.690650   10590
19    123           1751   ... 32.83593   11.150967   69127
20     37             43   ... 16.19596    3.308656   16238
21     19             41   ... 16.86853    3.840637   19140
22    962          39634   ... 42.76887   11.963266  771641
23     24             24   ... 16.83993    3.676808   19258
24      8             19   ... 16.93564    2.450687    7350
25     45             95   ... 20.27520    3.783950   31229
26     40             35   ... 13.60299    2.986901   19452
27     14             40   ... 17.82736    3.899083   13860
28    106             84   ... 14.70567    2.432571   39703
29     83            105   ... 15.53220    2.997030   36393
30     10             11   ... 11.36752    2.692308    6737
... ...           ...          ...        ...       ...
408  212            36     ... 13.43117   2.378543   29750
409  223            56     ... 21.93382   4.974496   30890
410 1965          1904     ... 24.85783   4.362722  137496
411  127           438     ... 37.41978   9.365039   71600
412   18             9     ... 15.74924   2.817824    6944
413   87           172     ... 24.46437   5.423401   30557
414  321            50     ... 18.59205   3.393293   34105
415  255           786     ... 24.63433   6.019312   57805
416   77            27     ... 15.52717   2.813520   15271
417  521          1004     ... 22.90651   4.936117  172392
418   34            38     ... 17.49934   3.147935   17254
419  369           985     ... 19.90644   4.370288  135919
420   82           114     ... 16.75598   3.019373   14748
421  121           148     ... 28.58809   5.380106   49388
422  288            79     ... 19.83392   3.970738   46193
423 2167            15     ... 17.94792   4.041667   13897
424 1762            70     ... 14.80780   2.455605   36389
425  357          2061     ... 20.83719   3.836386  101088
426   39            44     ... 15.06509   3.006166   18603
427   32            46     ... 17.55166   2.871216   24533
428   36            42     ... 18.94213   3.624948   25087
429 1534            38     ... 19.21186   4.315256   17446
430  201           494     ... 23.15690   6.082324   71553
431  122            33     ... 19.01689   4.022803   13532
432  208           337     ... 23.39090   4.014568   94143
433  672          2699     ... 35.39678   7.667090  299802
434  125            92     ... 16.54987   3.138596   44412
435   70            43     ... 15.06458   2.620907   19163
436  685          1728     ... 24.99550   5.659847  133950
437  481           722     ... 21.66638   4.583725   72685
    percpovertyknown percbelowpoverty percchildbelowpovert percadultpoverty
1   96.27478         13.151443        18.011717            11.009776
2   99.08714         32.244278        45.826514            27.385647
3   94.95697         12.068844        14.036061            10.852090
4   98.47757          7.209019        11.179536             5.536013
5   82.50514         13.520249        13.022889            11.143211
6   98.37200         10.399635        14.158819             8.179287
7   98.47802         15.149781        13.787761            12.932331
8   97.91729         11.710726        17.225462            10.027037
9   97.35060         13.875086        17.994784            11.914343
10  89.54429         15.572437        14.132234            17.562728
11  98.16956         11.708299        16.320612             9.569700
12  98.07801         12.007685        15.321547            10.131775
13  98.53389         16.774284        20.582578            14.464114
14  94.83267         10.223672        13.299402             9.253834
15  88.47688         16.748736        16.341941            18.792914
16  98.40269         14.198303        22.293497            11.665542
17  98.24805         10.537050        13.809825             8.870243
18  99.25023         12.049103        13.603185             9.822264
19  88.70169         13.544635         8.678238            17.047419
20  98.31678         10.315310        13.568426             7.955993
21  98.33539          9.629049        13.293543             7.924795
22  98.71748          2.714734         2.945252             2.399064
23  98.28017         16.003739        22.827628            14.480957
24  98.79032         12.204082        15.159868            10.950250
25  98.50177          8.994845        11.599832             6.974466
26  93.10295         13.618137        16.627635            12.134146
27  97.09282          9.264069        13.571228             7.325288
28  98.47218         20.764174        31.074742            19.313537
29  95.56985         15.494738        22.812225            13.996573
30  97.51049         21.433873        29.724656            20.005596
... ...              ...              ...                  ...
408 98.42520         12.094118        14.116632             9.634423
409 97.50939          9.617999        13.966707             8.109616
410 97.85496          6.202362         8.203007             5.022965
411 98.30979          2.180168         1.918955             1.938504
412 97.70649         12.615207        14.882122            10.123967
413 93.26110         10.416598        11.033134            10.337028
414 98.07897         11.822313        16.015585             9.756650
415 94.13729         12.895078        13.558998            13.182182
416 97.89103         10.889922        12.554958             8.145215
417 98.49058         10.151283        15.556437             8.429261
418 98.47611         13.440362        15.792812            12.637111
419 97.42599          9.877206        15.285761             8.143841
420 97.80489         16.578519        20.752427            15.806851
421 98.28262          6.402365         7.892108             4.972513
422 98.33528          9.691945        13.104104             8.148088
423 97.99732         20.544002        29.073570            19.195368
424 97.93309         11.297370        14.932266             9.105113
425 97.31509          6.486428         8.677912             5.146379
426 98.42336         12.664624        15.965037            10.265319
427 97.11040         10.675417        12.919976             7.884145
428 97.93106         15.824929        21.201105            13.449643
429 98.52601         14.736902        23.043367            14.251978
430 95.40400          9.641804         8.699613            10.926610
431 98.25733         15.866095        21.418598            13.642483
432 98.75692          3.237628         4.069854             2.584500
433 98.38767          3.121060         3.785820             2.590061
434 96.33004          8.488697        10.071411             6.953799
435 98.85478         13.786985        20.050708            11.695784
436 95.46038          8.804031        10.592031             8.660587
437 98.75008          8.525831        11.162997             7.375656
    percelderlypoverty inmetro category
1   12.443812          0       AAR
2   25.228976          0       LHR
3   12.697410          0       AAR
4    6.217047          1       ALU
5   19.200000          0       AAR
6   11.008586          0       AAR
7   21.085271          0       LAR
8    9.525052          0       AAR
9   13.660180          0       AAR
10   8.105017          1       HAU
11  11.490641          0       AAR
12  12.595420          0       AAR
13  17.670078          0       LAR
14   8.323176          1       LAU
15  10.993608          0       AAR
16  10.825269          1       AAU
17  10.803387          0       AAR
18  15.284626          0       AAR
19   6.453908          1       HAU
20  12.255345          0       AAR
21   8.714363          0       AAR
22   3.838249          1       HLU
23  11.762014          0       AAR
24  11.859528          0       AAR
25  10.517498          0       AAR
26  13.435829          0       AAR
27   8.787402          0       AAR
28  13.679486          0       LHR
29  11.019603          0       AAR
30  16.230032          0       LHR
... ...                ...     ...
408 15.588616          0       AAR
409  8.559414          0       AAR
410  6.855924          1       HLU
411  3.547067          1       HLU
412 15.131579          0       AAR
413  9.471418          1       HAU
414 11.164322          0       AAR
415 10.509441          0       AAR
416 14.769573          0       AAR
417  6.811663          1       AAU
418 12.354189          0       AAR
419  6.898250          1       AAU
420 13.128907          0       AAR
421  9.307219          1       HLU
422  9.140333          0       AAR
423 14.179318          0       AHR
424 11.949530          0       AAR
425  7.231785          1       ALU
426 13.889683          0       AAR
427 14.565299          0       AAR
428 14.571429          0       AAR
429  9.173228          0       AAR
430  6.894182          0       AAR
431 14.329455          0       AAR
432  4.280889          1       HLU
433  4.085479          1       HLU
434 10.338641          0       AAR
435 11.804558          0       AAR
436  6.661094          1       HAU
437  7.882918          0       AAR

In [123]:
str(midwest)

'data.frame':	437 obs. of  28 variables:
 $ PID                 : int  561 562 563 564 565 566 567 568 569 570 ...
 $ county              : chr  "ADAMS" "ALEXANDER" "BOND" "BOONE" ...
 $ state               : chr  "IL" "IL" "IL" "IL" ...
 $ area                : num  0.052 0.014 0.022 0.017 0.018 0.05 0.017 0.027 0.024 0.058 ...
 $ poptotal            : int  66090 10626 14991 30806 5836 35688 5322 16805 13437 173025 ...
 $ popdensity          : num  1271 759 681 1812 324 ...
 $ popwhite            : int  63917 7054 14477 29344 5264 35157 5298 16519 13384 146506 ...
 $ popblack            : int  1702 3496 429 127 547 50 1 111 16 16559 ...
 $ popamerindian       : int  98 19 35 46 14 65 8 30 8 331 ...
 $ popasian            : int  249 48 16 150 5 195 15 61 23 8033 ...
 $ popother            : int  124 9 34 1139 6 221 0 84 6 1596 ...
 $ percwhite           : num  96.7 66.4 96.6 95.3 90.2 ...
 $ percblack           : num  2.575 32.9 2.862 0.412 9.373 ...
 $ percamerindan       : num  0.148 0.179 0.233 0.149 0.24 ...
 $ percasian           : num  0.3768 0.4517 0.1067 0.4869 0.0857 ...
 $ percother           : num  0.1876 0.0847 0.2268 3.6973 0.1028 ...
 $ popadults           : int  43298 6724 9669 19272 3979 23444 3583 11323 8825 95971 ...
 $ perchsd             : num  75.1 59.7 69.3 75.5 68.9 ...
 $ percollege          : num  19.6 11.2 17 17.3 14.5 ...
 $ percprof            : num  4.36 2.87 4.49 4.2 3.37 ...
 $ poppovertyknown     : int  63628 10529 14235 30337 4815 35107 5241 16455 13081 154934 ...
 $ percpovertyknown    : num  96.3 99.1 95 98.5 82.5 ...
 $ percbelowpoverty    : num  13.15 32.24 12.07 7.21 13.52 ...
 $ percchildbelowpovert: num  18 45.8 14 11.2 13 ...
 $ percadultpoverty    : num  11.01 27.39 10.85 5.54 11.14 ...
 $ percelderlypoverty  : num  12.44 25.23 12.7 6.22 19.2 ...
 $ inmetro             : int  0 0 0 1 0 0 0 0 0 1 ...
 $ category            : chr  "AAR" "LHR" "AAR" "ALU" ...

In [124]:
# 전체 인구대비 미성년 인구
# poptotal L 전체 / popadults는 미성년 인구
midwest  <-  midwest %>% 
 mutate(rate_notadults = ((poptotal -  popadults )/ poptotal) * 100 )
midwest

    PID  county      state area  poptotal popdensity popwhite popblack
1   561  ADAMS       IL    0.052   66090   1270.9615   63917     1702
2   562  ALEXANDER   IL    0.014   10626    759.0000    7054     3496
3   563  BOND        IL    0.022   14991    681.4091   14477      429
4   564  BOONE       IL    0.017   30806   1812.1176   29344      127
5   565  BROWN       IL    0.018    5836    324.2222    5264      547
6   566  BUREAU      IL    0.050   35688    713.7600   35157       50
7   567  CALHOUN     IL    0.017    5322    313.0588    5298        1
8   568  CARROLL     IL    0.027   16805    622.4074   16519      111
9   569  CASS        IL    0.024   13437    559.8750   13384       16
10  570  CHAMPAIGN   IL    0.058  173025   2983.1897  146506    16559
11  571  CHRISTIAN   IL    0.042   34418    819.4762   34176       82
12  572  CLARK       IL    0.030   15921    530.7000   15842       10
13  573  CLAY        IL    0.028   14460    516.4286   14403        4
14  574  CLINTON     IL    0.029   33944   1170.4828   32688     1021
15  575  COLES       IL    0.030   51644   1721.4667   50177      925
16  576  COOK        IL    0.058 5105067  88018.3966 3204947  1317147
17  577  CRAWFORD    IL    0.026   19464    748.6154   19300       63
18  578  CUMBERLAND  IL    0.020   10670    533.5000   10627        5
19  579  DE KALB     IL    0.038   77932   2050.8421   72968     2069
20  580  DE WITT     IL    0.023   16516    718.0870   16387       25
21  581  DOUGLAS     IL    0.025   19464    778.5600   19280       16
22  582  DU PAGE     IL    0.020  781666  39083.3000  714905    15462
23  583  EDGAR       IL    0.036   19595    544.3056   19469       68
24  584  EDWARDS     IL    0.014    7440    531.4286    7401        6
25  585  EFFINGHAM   IL    0.028   31704   1132.2857   31523       12
26  586  FAYETTE     IL    0.044   20893    474.8409   20148      599
27  587  FORD        IL    0.030   14275    475.8333   14157       43
28  588  FRANKLIN    IL    0.025   40319   1612.7600   40068       36
29  589  FULTON      IL    0.052   38080    732.3077   37117      668
30  590  GALLATIN    IL    0.019    6909    363.6316    6842       42
... ...  ...         ...   ...   ...      ...        ...      ...
408 3023 OCONTO      WI    0.060  30226    503.7667   29926      18
409 3024 ONEIDA      WI    0.071  31679    446.1831   31320      58
410 3025 OUTAGAMIE   WI    0.037 140510   3797.5676  136043     206
411 3026 OZAUKEE     WI    0.015  72831   4855.4000   71676     492
412 3027 PEPIN       WI    0.014   7107    507.6429    7070       2
413 3028 PIERCE      WI    0.034  32765    963.6765   32366      82
414 3029 POLK        WI    0.055  34773    632.2364   34348      23
415 3030 PORTAGE     WI    0.048  61405   1279.2708   59972     161
416 3031 PRICE       WI    0.075  15600    208.0000   15479       7
417 3032 RACINE      WI    0.020 175034   8751.7000  152098   16999
418 3033 RICHLAND    WI    0.034  17521    515.3235   17411      12
419 3034 ROCK        WI    0.042 139510   3321.6667  130803    6638
420 3035 RUSK        WI    0.055  15079    274.1636   14821      31
421 3036 ST CROIX    WI    0.044  50251   1142.0682   49895      44
422 3037 SAUK        WI    0.050  46975    939.5000   46459      54
423 3038 SAWYER      WI    0.079  14181    179.5063   11962      18
424 3039 SHAWANO     WI    0.054  37157    688.0926   35251      42
425 3040 SHEBOYGAN   WI    0.032 103877   3246.1562  100389     430
426 3041 TAYLOR      WI    0.057  18901    331.5965   18807       2
427 3042 TREMPEALEAU WI    0.043  25263    587.5116   25160      12
428 3043 VERNON      WI    0.048  25617    533.6875   25509      12
429 3044 VILAS       WI    0.060  17707    295.1167   16116       9
430 3045 WALWORTH    WI    0.032  75000   2343.7500   72747     454
431 3046 WASHBURN    WI    0.050  13772    275.4400   13585      25
432 3047 WASHINGTON  WI    0.025  95328   3813.1200   94465     125
433 3048 WAUKESHA    WI    0.034 304715   8962.2059  298313    1096
434 3049 WAUPACA     WI    0.045  46104   1024.5333   45695      22
435 3050 WAUSHARA    WI    0.037  19385    523.9189   19094      29
436 3051 WINNEBAGO   WI    0.035 140320   4009.1429  136822     697
437 3052 WOOD        WI    0.048  73605   1533.4375   72157      90
    popamerindian popasian ... percprof  poppovertyknown percpovertyknown
1      98            249   ...  4.355859   63628         96.27478
2      19             48   ...  2.870315   10529         99.08714
3      35             16   ...  4.488572   14235         94.95697
4      46            150   ...  4.197800   30337         98.47757
5      14              5   ...  3.367680    4815         82.50514
6      65            195   ...  3.275891   35107         98.37200
7       8             15   ...  3.209601    5241         98.47802
8      30             61   ...  3.055727   16455         97.91729
9       8             23   ...  3.206799   13081         97.35060
10    331           8033   ... 17.757448  154934         89.54429
11     51             89   ...  3.089998   33788         98.16956
12     26             36   ...  2.776225   15615         98.07801
13     17             29   ...  2.788432   14248         98.53389
14     48            104   ...  2.875296   32190         94.83267
15     92            341   ...  8.144563   45693         88.47688
16  10289         188565   ...  8.329964 5023523         98.40269
17     34             48   ...  3.334084   19123         98.24805
18      6             26   ...  2.690650   10590         99.25023
19    123           1751   ... 11.150967   69127         88.70169
20     37             43   ...  3.308656   16238         98.31678
21     19             41   ...  3.840637   19140         98.33539
22    962          39634   ... 11.963266  771641         98.71748
23     24             24   ...  3.676808   19258         98.28017
24      8             19   ...  2.450687    7350         98.79032
25     45             95   ...  3.783950   31229         98.50177
26     40             35   ...  2.986901   19452         93.10295
27     14             40   ...  3.899083   13860         97.09282
28    106             84   ...  2.432571   39703         98.47218
29     83            105   ...  2.997030   36393         95.56985
30     10             11   ...  2.692308    6737         97.51049
... ...           ...          ...       ...             ...
408  212            36     ... 2.378543   29750          98.42520
409  223            56     ... 4.974496   30890          97.50939
410 1965          1904     ... 4.362722  137496          97.85496
411  127           438     ... 9.365039   71600          98.30979
412   18             9     ... 2.817824    6944          97.70649
413   87           172     ... 5.423401   30557          93.26110
414  321            50     ... 3.393293   34105          98.07897
415  255           786     ... 6.019312   57805          94.13729
416   77            27     ... 2.813520   15271          97.89103
417  521          1004     ... 4.936117  172392          98.49058
418   34            38     ... 3.147935   17254          98.47611
419  369           985     ... 4.370288  135919          97.42599
420   82           114     ... 3.019373   14748          97.80489
421  121           148     ... 5.380106   49388          98.28262
422  288            79     ... 3.970738   46193          98.33528
423 2167            15     ... 4.041667   13897          97.99732
424 1762            70     ... 2.455605   36389          97.93309
425  357          2061     ... 3.836386  101088          97.31509
426   39            44     ... 3.006166   18603          98.42336
427   32            46     ... 2.871216   24533          97.11040
428   36            42     ... 3.624948   25087          97.93106
429 1534            38     ... 4.315256   17446          98.52601
430  201           494     ... 6.082324   71553          95.40400
431  122            33     ... 4.022803   13532          98.25733
432  208           337     ... 4.014568   94143          98.75692
433  672          2699     ... 7.667090  299802          98.38767
434  125            92     ... 3.138596   44412          96.33004
435   70            43     ... 2.620907   19163          98.85478
436  685          1728     ... 5.659847  133950          95.46038
437  481           722     ... 4.583725   72685          98.75008
    percbelowpoverty percchildbelowpovert percadultpoverty percelderlypoverty
1   13.151443        18.011717            11.009776        12.443812
2   32.244278        45.826514            27.385647        25.228976
3   12.068844        14.036061            10.852090        12.697410
4    7.209019        11.179536             5.536013         6.217047
5   13.520249        13.022889            11.143211        19.200000
6   10.399635        14.158819             8.179287        11.008586
7   15.149781        13.787761            12.932331        21.085271
8   11.710726        17.225462            10.027037         9.525052
9   13.875086        17.994784            11.914343        13.660180
10  15.572437        14.132234            17.562728         8.105017
11  11.708299        16.320612             9.569700        11.490641
12  12.007685        15.321547            10.131775        12.595420
13  16.774284        20.582578            14.464114        17.670078
14  10.223672        13.299402             9.253834         8.323176
15  16.748736        16.341941            18.792914        10.993608
16  14.198303        22.293497            11.665542        10.825269
17  10.537050        13.809825             8.870243        10.803387
18  12.049103        13.603185             9.822264        15.284626
19  13.544635         8.678238            17.047419         6.453908
20  10.315310        13.568426             7.955993        12.255345
21   9.629049        13.293543             7.924795         8.714363
22   2.714734         2.945252             2.399064         3.838249
23  16.003739        22.827628            14.480957        11.762014
24  12.204082        15.159868            10.950250        11.859528
25   8.994845        11.599832             6.974466        10.517498
26  13.618137        16.627635            12.134146        13.435829
27   9.264069        13.571228             7.325288         8.787402
28  20.764174        31.074742            19.313537        13.679486
29  15.494738        22.812225            13.996573        11.019603
30  21.433873        29.724656            20.005596        16.230032
... ...              ...                  ...              ...
408 12.094118        14.116632             9.634423        15.588616
409  9.617999        13.966707             8.109616         8.559414
410  6.202362         8.203007             5.022965         6.855924
411  2.180168         1.918955             1.938504         3.547067
412 12.615207        14.882122            10.123967        15.131579
413 10.416598        11.033134            10.337028         9.471418
414 11.822313        16.015585             9.756650        11.164322
415 12.895078        13.558998            13.182182        10.509441
416 10.889922        12.554958             8.145215        14.769573
417 10.151283        15.556437             8.429261         6.811663
418 13.440362        15.792812            12.637111        12.354189
419  9.877206        15.285761             8.143841         6.898250
420 16.578519        20.752427            15.806851        13.128907
421  6.402365         7.892108             4.972513         9.307219
422  9.691945        13.104104             8.148088         9.140333
423 20.544002        29.073570            19.195368        14.179318
424 11.297370        14.932266             9.105113        11.949530
425  6.486428         8.677912             5.146379         7.231785
426 12.664624        15.965037            10.265319        13.889683
427 10.675417        12.919976             7.884145        14.565299
428 15.824929        21.201105            13.449643        14.571429
429 14.736902        23.043367            14.251978         9.173228
430  9.641804         8.699613            10.926610         6.894182
431 15.866095        21.418598            13.642483        14.329455
432  3.237628         4.069854             2.584500         4.280889
433  3.121060         3.785820             2.590061         4.085479
434  8.488697        10.071411             6.953799        10.338641
435 13.786985        20.050708            11.695784        11.804558
436  8.804031        10.592031             8.660587         6.661094
437  8.525831        11.162997             7.375656         7.882918
    inmetro category rate_notadults
1   0       AAR      34.48631
2   0       LHR      36.72125
3   0       AAR      35.50130
4   1       ALU      37.44076
5   0       AAR      31.81974
6   0       AAR      34.30845
7   0       LAR      32.67569
8   0       AAR      32.62124
9   0       AAR      34.32314
10  1       HAU      44.53345
11  0       AAR      33.33430
12  0       AAR      32.57961
13  0       LAR      33.28492
14  1       LAU      36.47478
15  0       AAR      43.58299
16  1       AAU      35.51515
17  0       AAR      31.58138
18  0       AAR      36.95408
19  1       HAU      46.34168
20  0       AAR      33.75515
21  0       AAR      35.52199
22  1       HLU      35.73713
23  0       AAR      33.23807
24  0       AAR      32.54032
25  0       AAR      38.56611
26  0       AAR      33.49926
27  0       AAR      32.80560
28  0       LHR      32.50329
29  0       AAR      32.79412
30  0       LHR      32.26227
... ...     ...      ...
408 0       AAR      34.62582
409 0       AAR      30.07039
410 1       HLU      38.30404
411 1       HLU      35.38740
412 0       AAR      35.58463
413 1       HAU      43.16191
414 0       AAR      35.25149
415 0       AAR      42.99487
416 0       AAR      33.24359
417 1       AAU      36.81628
418 0       AAR      35.45460
419 1       AAU      36.87048
420 0       AAR      35.64560
421 1       HLU      38.56242
422 0       AAR      35.39755
423 0       AHR      32.30379
424 0       AAR      34.67987
425 1       ALU      35.56033
426 0       AAR      38.22549
427 0       AAR      34.10125
428 0       AAR      34.09455
429 0       AAR      27.62749
430 0       AAR      37.67733
431 0       AAR      32.49347
432 1       HLU      37.49685
433 1       HLU      35.73109
434 0       AAR      34.69330
435 0       AAR      31.30771
436 1       HAU      36.60205
437 0       AAR      36.42280

In [125]:
midwest %>% 
 arrange(desc(rate_notadults), by=county)

    PID  county      state area  poptotal popdensity popwhite popblack
1   1233 ISABELLA    MI    0.034  54624   1606.5882   52212     635
2   3020 MENOMINEE   WI    0.021   3890    185.2381     416       0
3   2013 ATHENS      OH    0.030  59549   1984.9667   56163    1678
4   1250 MECOSTA     MI    0.034  37308   1097.2941   35739     978
5    715 MONROE      IN    0.024 108978   4540.7500  102752    2835
6    599 JACKSON     IL    0.036  61067   1696.3056   51991    6342
7    741 TIPPECANOE  IN    0.030 130598   4353.2667  122013    2660
8    615 MCDONOUGH   IL    0.034  35244   1036.5882   32992    1254
9    579 DE KALB     IL    0.038  77932   2050.8421   72968    2069
10  2046 HOLMES      OH    0.025  32849   1313.9600   32706      52
11   706 LAGRANGE    IN    0.022  29477   1339.8636   29156      44
12  2997 DUNN        WI    0.052  35909    690.5577   34929     172
13   570 CHAMPAIGN   IL    0.058 173025   2983.1897  146506   16559
14  1229 INGHAM      MI    0.034 281912   8291.5294  237183   27837
15   575 COLES       IL    0.030  51644   1721.4667   50177     925
16   617 MCLEAN      IL    0.068 129180   1899.7059  121057    5563
17  2095 WOOD        OH    0.037 113269   3061.3243  109303    1168
18  3028 PIERCE      WI    0.034  32765    963.6765   32366      82
19  3030 PORTAGE     WI    0.048  61405   1279.2708   59972     161
20  2998 EAU CLAIRE  WI    0.038  85183   2241.6579   82202     238
21  2075 PORTAGE     OH    0.030 142585   4752.8333  136998    3906
22  1227 HOUGHTON    MI    0.060  35446    590.7667   34469     158
23   663 ADAMS       IN    0.021  31095   1480.7143   30530      36
24  1230 IONIA       MI    0.034  57024   1677.1765   53141    3003
25  1266 OTTAWA      MI    0.033 187768   5689.9394  179675     997
26   680 DELAWARE    IN    0.023 119659   5202.5652  111232    7167
27  1277 WASHTENAW   MI    0.041 282937   6900.9024  236390   31720
28  3002 GRANT       WI    0.069  49264    713.9710   48838      76
29  2077 PUTNAM      OH    0.029  33819   1166.1724   33197      26
30  2041 HARDIN      OH    0.028  31111   1111.1071   30661     236
... ...  ...         ...   ...   ...      ...        ...      ...
408  643 SALINE      IL    0.022 26551    1206.8636  25452     931
409  645 SCHUYLER    IL    0.026  7498     288.3846   7479       2
410 1273 SCHOOLCRAFT MI    0.075  8302     110.6933   7755       7
411  565 BROWN       IL    0.018  5836     324.2222   5264     547
412  624 MASSAC      IL    0.014 14752    1053.7143  13804     870
413 1206 BENZIE      MI    0.020 12200     610.0000  11863      30
414  577 CRAWFORD    IL    0.026 19464     748.6154  19300      63
415 2015 BELMONT     OH    0.031 71074    2292.7097  69520    1308
416  611 LAWRENCE    IL    0.022 15972     726.0000  15759     151
417  651 UNION       IL    0.024 17619     734.1250  17313     122
418 3050 WAUSHARA    WI    0.037 19385     523.9189  19094      29
419 1247 MANISTEE    MI    0.032 21265     664.5312  20851      54
420  593 HAMILTON    IL    0.025  8499     339.9600   8462       3
421 3019 MARQUETTE   WI    0.027 12321     456.3333  12174      31
422 1239 LAKE        MI    0.035  8583     245.2286   7337    1146
423 2987 BURNETT     WI    0.053 13084     246.8679  12497      22
424 1223 GOGEBIC     MI    0.068 18052     265.4706  17486     243
425 1264 OSCODA      MI    0.033  7842     237.6364   7781       2
426  657 WHITE       IL    0.029 16522     569.7241  16397      41
427  604 JOHNSON     IL    0.020 11347     567.3500  10230    1046
428 3024 ONEIDA      WI    0.071 31679     446.1831  31320      58
429 1262 ONTONAGON   MI    0.078  8854     113.5128   8723       4
430 1256 MONTMORENCY MI    0.033  8936     270.7879   8861       1
431 3006 IRON        WI    0.047  6153     130.9149   6121       1
432 3044 VILAS       WI    0.060 17707     295.1167  16116       9
433 2981 ADAMS       WI    0.041 15682     382.4878  15001     375
434 1197 ALCONA      MI    0.041 10145     247.4390  10026      27
435 1232 IRON        MI    0.070 13175     188.2143  13028       4
436 1268 ROSCOMMON   MI    0.034 19776     581.6471  19597      37
437 1238 KEWEENAW    MI    0.020  1701      85.0500   1688       1
    popamerindian popasian ... percprof   poppovertyknown percpovertyknown
1   1020            456    ... 10.0030198  48498          88.78515
2   3469              0    ...  0.5202914   3820          98.20051
3    167           1374    ... 12.0447994  51002          85.64711
4    258            187    ...  7.8453039  32627          87.45309
5    216           2713    ... 17.2012272  93693          85.97423
6    109           2178    ... 14.0898918  54230          88.80410
7    320           4821    ... 15.2571296 114062          87.33824
8     65            802    ... 10.3598807  28821          81.77562
9    123           1751    ... 11.1509673  69127          88.70169
10    24             43    ...  1.7266592  31830          96.89793
11    59             92    ...  3.4658385  28954          98.22574
12    95            633    ...  7.5069603  32837          91.44504
13   331           8033    ... 17.7574476 154934          89.54429
14  1941           7562    ... 12.8599826 261491          92.75625
15    92            341    ...  8.1445634  45693          88.47688
16   203           1624    ...  9.0039338 117663          91.08453
17   197           1028    ...  8.3354150 104553          92.30504
18    87            172    ...  5.4234012  30557          93.26110
19   255            786    ...  6.0193121  57805          94.13729
20   467           2124    ...  7.5563483  80458          94.45312
21   292           1191    ...  6.5868046 133447          93.59119
22   153            610    ...  7.3282960  32448          91.54206
23    42             60    ...  4.8622992  30490          98.05435
24   221            120    ...  3.4004661  51695          90.65481
25   638           2451    ...  6.1596395 181937          96.89457
26   274            641    ...  8.3884491 111645          93.30263
27  1076          11724    ... 20.7913213 261261          92.33893
28    76            234    ...  5.2434842  46314          94.01185
29    44             25    ...  2.8060715  33390          98.73148
30    66            115    ...  4.3251385  29111          93.57141
... ...           ...          ...        ...             ...
408   66           40      ... 3.634850   25545           96.21107
409    9            6      ... 2.750491    7365           98.22619
410  519           13      ... 2.764487    8218           98.98820
411   14            5      ... 3.367680    4815           82.50514
412   37           31      ... 2.930075   14348           97.26139
413  237           35      ... 4.680187   12077           98.99180
414   34           48      ... 3.334084   19123           98.24805
415   81          129      ... 3.227464   69952           98.42136
416   31           21      ... 1.945205   15347           96.08690
417   34           53      ... 4.002646   16823           95.48215
418   70           43      ... 2.620907   19163           98.85478
419  189           54      ... 3.392845   21000           98.75382
420   11           21      ... 2.611367    8383           98.63513
421   49           18      ... 2.576774   12182           98.87184
422   81            9      ... 2.006407    8387           97.71642
423  532           24      ... 2.996130   12816           97.95170
424  283           26      ... 3.352805   17385           96.30512
425   41            5      ... 2.687281    7718           98.41877
426   37           35      ... 3.248625   16152           97.76056
427   26           14      ... 3.433476    9180           80.90244
428  223           56      ... 4.974496   30890           97.50939
429  109           15      ... 2.662149    8712           98.39621
430   48           10      ... 2.755216    8803           98.51164
431   25            2      ... 2.675961    6021           97.85470
432 1534           38      ... 4.315256   17446           98.52601
433  125           56      ... 2.390578   14534           92.67951
434   56           26      ... 3.243757   10040           98.96501
435  102           32      ... 3.283302   12886           97.80645
436  101           23      ... 2.812608   19602           99.12015
437    4            6      ... 3.574204    1696           99.70606
    percbelowpoverty percchildbelowpovert percadultpoverty percelderlypoverty
1   24.854633        21.269687            28.479147        13.966294
2   48.691099        64.308477            43.312464        18.218623
3   28.673385        29.258116            31.744281        14.324955
4   25.068195        25.543614            28.229964        13.168572
5   19.439019        14.346337            22.998998         9.575163
6   28.371750        26.392211            32.458483        13.815301
7   14.381652        10.567515            17.188413         7.864945
8   19.052080        16.009317            22.403382        12.884384
9   13.544635         8.678238            17.047419         6.453908
10  17.244738        24.517113            12.352242        15.357939
11  11.507909        15.961557             7.967512        13.474640
12  16.633675        15.195467            18.661388        11.896260
13  15.572437        14.132234            17.562728         8.105017
14  16.618163        18.947244            17.066058         9.398272
15  16.748736        16.341941            18.792914        10.993608
16  11.875441        10.010509            13.715404         7.266603
17  10.572628         8.760440            12.223590         6.931427
18  10.416598        11.033134            10.337028         9.471418
19  12.895078        13.558998            13.182182        10.509441
20  15.943722        18.743018            16.768501         8.575147
21  11.908848        13.381445            12.153734         7.978635
22  21.036736        21.198980            23.697149        14.578494
23  11.636602        17.194524             9.101888         8.714027
24  11.329916        14.965088             9.346290        11.109629
25   5.986688         6.297882             5.891174         5.682466
26  16.747727        17.661107            17.889860        11.767964
27  12.162933        10.797816            13.455456         7.174777
28  13.715075        15.155223            12.974722        13.628639
29   5.756214         7.140180             4.238700         7.951762
30  16.382124        21.816574            14.936820        12.594554
... ...              ...                  ...              ...
408 20.183989        26.69911             18.694407        16.846582
409 16.496945        21.91342             13.646113        16.780045
410 16.609881        20.72882             15.321212        14.898990
411 13.520249        13.02289             11.143211        19.200000
412 16.741009        22.98083             14.968237        14.328358
413 12.859154        18.64117             11.304757        10.327456
414 10.537050        13.80983              8.870243        10.803387
415 17.419087        25.84997             15.762905        12.575324
416 19.847527        31.11287             16.759706        14.883216
417 18.159662        24.90020             14.679004        19.010096
418 13.786985        20.05071             11.695784        11.804558
419 17.623810        25.93546             15.384615        14.141214
420 19.849696        21.92327             17.050133        23.141967
421 11.607289        15.64303              9.678511        11.458647
422 26.409920        37.69860             25.070712        18.876497
423 15.488452        21.02937             13.937947        13.168847
424 14.880644        19.54478             13.598734        13.257945
425 17.802540        24.35065             17.000267        13.518606
426 19.056464        27.03405             16.487238        16.716196
427 15.555556        18.53506             12.266501        19.877532
428  9.617999        13.96671              8.109616         8.559414
429 13.188705        16.51637             11.808036        12.800000
430 17.516756        26.83284             16.208251        12.402235
431 13.070918        15.64679             12.179042        12.662338
432 14.736902        23.04337             14.251978         9.173228
433 14.435118        22.30083             13.310056        10.186757
434 17.250996        27.20450             16.617399        11.506936
435 17.119354        23.32412             14.456165        16.512236
436 18.054280        26.03709             17.995797        13.074424
437 20.577830        21.88450             21.276596        19.024390
    inmetro category rate_notadults
1   0       AHR      51.50117
2   0       LHR      50.59126
3   0       AHR      49.32073
4   0       AHR      49.05918
5   1       HHU      47.35818
6   0       AHR      47.31688
7   1       HAU      47.05279
8   0       HHR      46.70298
9   1       HAU      46.34168
10  0       LAR      45.87354
11  0       LAR      45.38114
12  0       AAR      44.98594
13  1       HAU      44.53345
14  1       HAU      43.61148
15  0       AAR      43.58299
16  1       HAU      43.52299
17  1       HAU      43.45143
18  1       HAU      43.16191
19  0       AAR      42.99487
20  1       HAU      42.08234
21  1       AAU      41.98127
22  0       AHR      41.75365
23  1       AAU      41.73018
24  0       AAR      41.31243
25  1       ALU      41.02456
26  1       AAU      40.99148
27  1       HAU      40.90062
28  0       AAR      40.80870
29  0       ALR      40.77885
30  0       AAR      40.24943
... ...     ...      ...
408 0       LHR      32.13062
409 0       AAR      32.11523
410 0       AAR      32.02843
411 0       AAR      31.81974
412 0       LAR      31.75163
413 0       AAR      31.69672
414 0       AAR      31.58138
415 1       AAU      31.55725
416 0       AHR      31.44252
417 0       LHR      31.36954
418 0       AAR      31.30771
419 0       AAR      31.25323
420 0       LHR      31.06248
421 0       AAR      31.02021
422 0       LHR      30.89829
423 0       AAR      30.86976
424 0       AAR      30.77221
425 0       LHR      30.71920
426 0       LHR      30.69241
427 0       LAR      30.18419
428 0       AAR      30.07039
429 0       AAR      29.99774
430 0       LAR      29.73366
431 0       AAR      27.72631
432 0       AAR      27.62749
433 0       LAR      27.44548
434 0       AAR      27.37309
435 0       AAR      27.18027
436 0       AHR      27.00748
437 0       LHR      24.33862

In [126]:
# 분류표
# 미성년 비율등급 
# large = 40dltkd
# middle= 30 - 40
# small = 30 미만
midwest <- midwest %>% 
            mutate(rank = ifelse( rate_notadults >= 40, 'large'
                                 , ifelse( rate_notadults < 40 & rate_notadults >= 30 ,'middle', 'small' ) 
                                ) 
                  )

In [127]:
str(midwest)

'data.frame':	437 obs. of  30 variables:
 $ PID                 : int  561 562 563 564 565 566 567 568 569 570 ...
 $ county              : chr  "ADAMS" "ALEXANDER" "BOND" "BOONE" ...
 $ state               : chr  "IL" "IL" "IL" "IL" ...
 $ area                : num  0.052 0.014 0.022 0.017 0.018 0.05 0.017 0.027 0.024 0.058 ...
 $ poptotal            : int  66090 10626 14991 30806 5836 35688 5322 16805 13437 173025 ...
 $ popdensity          : num  1271 759 681 1812 324 ...
 $ popwhite            : int  63917 7054 14477 29344 5264 35157 5298 16519 13384 146506 ...
 $ popblack            : int  1702 3496 429 127 547 50 1 111 16 16559 ...
 $ popamerindian       : int  98 19 35 46 14 65 8 30 8 331 ...
 $ popasian            : int  249 48 16 150 5 195 15 61 23 8033 ...
 $ popother            : int  124 9 34 1139 6 221 0 84 6 1596 ...
 $ percwhite           : num  96.7 66.4 96.6 95.3 90.2 ...
 $ percblack           : num  2.575 32.9 2.862 0.412 9.373 ...
 $ percamerindan       : num  0.148 0.179 0.233 0.149 0.24 ...
 $ percasian           : num  0.3768 0.4517 0.1067 0.4869 0.0857 ...
 $ percother           : num  0.1876 0.0847 0.2268 3.6973 0.1028 ...
 $ popadults           : int  43298 6724 9669 19272 3979 23444 3583 11323 8825 95971 ...
 $ perchsd             : num  75.1 59.7 69.3 75.5 68.9 ...
 $ percollege          : num  19.6 11.2 17 17.3 14.5 ...
 $ percprof            : num  4.36 2.87 4.49 4.2 3.37 ...
 $ poppovertyknown     : int  63628 10529 14235 30337 4815 35107 5241 16455 13081 154934 ...
 $ percpovertyknown    : num  96.3 99.1 95 98.5 82.5 ...
 $ percbelowpoverty    : num  13.15 32.24 12.07 7.21 13.52 ...
 $ percchildbelowpovert: num  18 45.8 14 11.2 13 ...
 $ percadultpoverty    : num  11.01 27.39 10.85 5.54 11.14 ...
 $ percelderlypoverty  : num  12.44 25.23 12.7 6.22 19.2 ...
 $ inmetro             : int  0 0 0 1 0 0 0 0 0 1 ...
 $ category            : chr  "AAR" "LHR" "AAR" "ALU" ...
 $ rate_notadults      : num  34.5 36.7 35.5 37.4 31.8 ...
 $ rank                : chr  "middle" "middle" "middle" "middle" ...

In [129]:
midwest %>%
 group_by(rank) %>% 
 summarise( rank_count =  n())

  rank   rank_count
1 large   32
2 middle 396
3 small    9

In [132]:
midwest %>%
 select(state, county, poptotal, popasian) %>% 
 mutate( rate_asian = ( popasian / poptotal) *100 ) %>% 
 head(10)

   state county    poptotal popasian rate_asian
1  IL    ADAMS      66090    249     0.37675897
2  IL    ALEXANDER  10626     48     0.45172219
3  IL    BOND       14991     16     0.10673071
4  IL    BOONE      30806    150     0.48691813
5  IL    BROWN       5836      5     0.08567512
6  IL    BUREAU     35688    195     0.54640215
7  IL    CALHOUN     5322     15     0.28184893
8  IL    CARROLL    16805     61     0.36298721
9  IL    CASS       13437     23     0.17116916
10 IL    CHAMPAIGN 173025   8033     4.64268169